// Auto-generated by the adk-fluent codegen pipeline.
// Do not edit by hand — re-run `just ts-generate`.

import { BuilderBase } from "../core/builder-base.js";

/**
 * Configuration for the A2aAgentExecutor.
 */
export class A2aAgentExecutorConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``a2a_part_converter`` field.
   */
  a2aPartConverter(value: (...args: unknown[]) => unknown): this {
    return this._setConfig("a2a_part_converter", value);
  }

  /**
   * Set the ``gen_ai_part_converter`` field.
   */
  genAiPartConverter(value: (...args: unknown[]) => unknown): this {
    return this._setConfig("gen_ai_part_converter", value);
  }

  /**
   * Set the ``request_converter`` field.
   */
  requestConverter(value: (...args: unknown[]) => unknown): this {
    return this._setConfig("request_converter", value);
  }

  /**
   * Set the ``event_converter`` field.
   */
  eventConverter(value: (...args: unknown[]) => unknown): this {
    return this._setConfig("event_converter", value);
  }

  /**
   * Configuration for the A2aAgentExecutor. Resolve into a native ADK _ADK_A2aAgentExecutorConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("A2aAgentExecutorConfig");
  }
}

/**
 * The config for the YAML schema to create an agent.
 */
export class AgentConfig extends BuilderBase {
  constructor(root: string) {
    super(root);
  }

  /**
   * The config for the YAML schema to create an agent. Resolve into a native ADK _ADK_AgentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("AgentConfig");
  }
}

/**
 * The config for the YAML schema of a BaseAgent.
 */
export class BaseAgentConfig extends BuilderBase {
  constructor(name: string) {
    super(name);
  }

  /**
   * Set agent description (metadata for transfer routing and topology display — NOT sent to the LLM as instruction). Always set this on sub-agents so the coordinator LLM can pick the right specialist.
   */
  describe(value: string): this {
    return this._setConfig("description", value);
  }

  /**
   * Required. The class of the agent. The value is used to differentiate among different agent classes.
   */
  agentClass(value: unknown): this {
    return this._setConfig("agent_class", value);
  }

  /**
   * Optional. The sub-agents of the agent.
   */
  subAgents(value: unknown): this {
    return this._setConfig("sub_agents", value);
  }

  /**
   * Optional. The before_agent_callbacks of the agent.
   * 
   * Example:
   * 
   *   ```
   *   before_agent_callbacks:
   *     - name: my_library.security_callbacks.before_agent_callback
   *   ```
   */
  beforeAgentCallbacks(value: unknown): this {
    return this._setConfig("before_agent_callbacks", value);
  }

  /**
   * Optional. The after_agent_callbacks of the agent.
   */
  afterAgentCallbacks(value: unknown): this {
    return this._setConfig("after_agent_callbacks", value);
  }

  /**
   * Append to ``sub_agents`` (lazy — built at .build() time).
   */
  subAgent(value: unknown): this {
    return this._addToList("sub_agents", value);
  }

  /**
   * Append to ``before_agent_callbacks`` (lazy — built at .build() time).
   */
  beforeAgentCallback(value: unknown): this {
    return this._addToList("before_agent_callbacks", value);
  }

  /**
   * Append to ``after_agent_callbacks`` (lazy — built at .build() time).
   */
  afterAgentCallback(value: unknown): this {
    return this._addToList("after_agent_callbacks", value);
  }

  /**
   * The config for the YAML schema of a BaseAgent. Resolve into a native ADK _ADK_BaseAgentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BaseAgentConfig");
  }
}

/**
 * The config for the reference to another agent.
 */
export class AgentRefConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``config_path`` field.
   */
  configPath(value: string | undefined): this {
    return this._setConfig("config_path", value);
  }

  /**
   * Set the ``code`` field.
   */
  code(value: string | undefined): this {
    return this._setConfig("code", value);
  }

  /**
   * The config for the reference to another agent. Resolve into a native ADK _ADK_AgentRefConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("AgentRefConfig");
  }
}

/**
 * An argument passed to a function or a class's constructor.
 */
export class ArgumentConfig extends BuilderBase {
  constructor(value: string) {
    super(value);
  }

  /**
   * Set the ``name`` field.
   */
  name_(value: string | undefined): this {
    return this._setConfig("name", value);
  }

  /**
   * An argument passed to a function or a class's constructor. Resolve into a native ADK _ADK_ArgumentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ArgumentConfig");
  }
}

/**
 * Code reference config for a variable, a function, or a class.
 */
export class CodeConfig extends BuilderBase {
  constructor(name: string) {
    super(name);
  }

  /**
   * Set the ``args`` field.
   */
  args(value: unknown): this {
    return this._setConfig("args", value);
  }

  /**
   * Append to ``args`` (lazy — built at .build() time).
   */
  arg(value: unknown): this {
    return this._addToList("args", value);
  }

  /**
   * Code reference config for a variable, a function, or a class. Resolve into a native ADK _ADK_CodeConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("CodeConfig");
  }
}

/**
 * Configuration for context caching across all agents in an app.
 */
export class ContextCacheConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Maximum number of invocations to reuse the same cache before refreshing it
   */
  cacheIntervals(value: number): this {
    return this._setConfig("cache_intervals", value);
  }

  /**
   * Time-to-live for cache in seconds
   */
  ttlSeconds(value: number): this {
    return this._setConfig("ttl_seconds", value);
  }

  /**
   * Minimum estimated request tokens required to enable caching. This compares against the estimated total tokens of the request (system instruction + tools + contents). Context cache storage may have cost. Set higher to avoid caching small requests where overhead may exceed benefits.
   */
  minTokens(value: number): this {
    return this._setConfig("min_tokens", value);
  }

  /**
   * Configuration for context caching across all agents in an app. Resolve into a native ADK _ADK_ContextCacheConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ContextCacheConfig");
  }
}

/**
 * The config for the YAML schema of a LlmAgent.
 */
export class LlmAgentConfig extends BuilderBase {
  constructor(name: string, instruction: string) {
    super(name);
    this._config.set("instruction", instruction);
  }

  /**
   * Set agent description (metadata for transfer routing and topology display — NOT sent to the LLM as instruction). Always set this on sub-agents so the coordinator LLM can pick the right specialist.
   */
  describe(value: string): this {
    return this._setConfig("description", value);
  }

  /**
   * Required. LlmAgent.instruction. Dynamic instructions with placeholder support. Behavior: if static_instruction is None, goes to system_instruction; if static_instruction is set, goes to user content after static content.
   */
  instruct(value: string): this {
    return this._setConfig("instruction", value);
  }

  /**
   * Set cached instruction. When set, ``.instruct()`` text moves from system to user content, enabling context caching. Use for large, stable prompt sections that rarely change.
   */
  static_(value: unknown): this {
    return this._setConfig("static_instruction", value);
  }

  /**
   * Set cached instruction. When set, ``.instruct()`` text moves from system to user content, enabling context caching. Use for large, stable prompt sections that rarely change.
   */
  staticInstruct(value: unknown): this {
    return this._setConfig("static_instruction", value);
  }

  /**
   * The value is used to uniquely identify the LlmAgent class. If it is empty, it is by default an LlmAgent.
   */
  agentClass(value: string): this {
    return this._setConfig("agent_class", value);
  }

  /**
   * Optional. The sub-agents of the agent.
   */
  subAgents(value: unknown): this {
    return this._setConfig("sub_agents", value);
  }

  /**
   * Optional. The before_agent_callbacks of the agent.
   * 
   * Example:
   * 
   *   ```
   *   before_agent_callbacks:
   *     - name: my_library.security_callbacks.before_agent_callback
   *   ```
   */
  beforeAgentCallbacks(value: unknown): this {
    return this._setConfig("before_agent_callbacks", value);
  }

  /**
   * Optional. The after_agent_callbacks of the agent.
   */
  afterAgentCallbacks(value: unknown): this {
    return this._setConfig("after_agent_callbacks", value);
  }

  /**
   * Optional. LlmAgent.model. Provide a model name string (e.g. "gemini-2.0-flash"). If not set, the model will be inherited from the ancestor or fall back to the system default (gemini-2.5-flash unless overridden via LlmAgent.set_default_model). To construct a model instance from code, use model_code.
   */
  model(value: string | undefined): this {
    return this._setConfig("model", value);
  }

  /**
   * Optional. A CodeConfig that instantiates a BaseLlm implementation such as LiteLlm with custom arguments (API base, fallbacks, etc.). Cannot be set together with `model`.
   */
  modelCode(value: unknown | undefined): this {
    return this._setConfig("model_code", value);
  }

  /**
   * Prevent this agent from transferring control back to its parent. Also forces an auto-handoff back to parent on the next turn. Equivalent to ``.stay()``. See also ``.isolate()``.
   */
  disallowTransferToParent(value: boolean | undefined): this {
    return this._setConfig("disallow_transfer_to_parent", value);
  }

  /**
   * Prevent this agent from transferring control to sibling agents. Equivalent to ``.no_peers()``. See also ``.isolate()``.
   */
  disallowTransferToPeers(value: boolean | undefined): this {
    return this._setConfig("disallow_transfer_to_peers", value);
  }

  /**
   * Schema defining the expected input structure when this agent is invoked as a tool by another agent.
   * 
   * When another agent invokes this agent via ``AgentTool``, the calling
   * agent's arguments are validated against this Pydantic model. Irrelevant
   * for top-level agents — only for agents that serve as tools.
   * 
   * .. note::
   * 
   *    Prefer ``.accepts(Model)`` over this method for clarity.
   *    ``.accepts()`` is the recommended alias on BuilderBase.
   * 
   *    - ``.accepts(Model)`` → tool-mode input validation (same as this, HAS runtime effect)
   *    - ``.consumes(Model)`` → contract annotation (NO runtime effect)
   */
  inputSchema(value: unknown | undefined): this {
    return this._setConfig("input_schema", value);
  }

  /**
   * Force the LLM to respond with structured JSON matching a Pydantic model.
   * 
   * When set, the agent replies **only** with JSON data conforming to
   * this schema. The agent **cannot use tools** while ``output_schema``
   * is active.
   * 
   * .. note::
   * 
   *    Prefer ``.returns(Model)`` or ``@ Model`` over this method.
   *    ``.returns()`` sets the same ADK constraint AND automatically
   *    parses the response in ``.ask()`` calls. This method sets the
   *    raw ADK field without automatic parsing.
   * 
   *    - ``.returns(Model)`` / ``@ Model`` → LLM constraint + parsing (HAS runtime effect)
   *    - ``.output_schema(Model)`` → LLM constraint only (raw field)
   *    - ``.writes(key)`` → stores text in state (no format constraint)
   *    - ``.produces(Model)`` → contract annotation (NO runtime effect)
   */
  outputSchema(value: unknown | undefined): this {
    return this._setConfig("output_schema", value);
  }

  /**
   * Session state key where the agent's response text is stored. Prefer ``.writes(key)`` — the idiomatic alias on BuilderBase.
   */
  outputKey(value: string | undefined): this {
    return this._setConfig("output_key", value);
  }

  /**
   * Optional. LlmAgent.include_contents.
   */
  includeContents(value: unknown): this {
    return this._setConfig("include_contents", value);
  }

  /**
   * Optional. LlmAgent.tools.
   * 
   * Examples:
   * 
   *   For ADK built-in tools in `google.adk.tools` package, they can be referenced
   *   directly with the name:
   * 
   *     ```
   *     tools:
   *       - name: google_search
   *       - name: load_memory
   *     ```
   * 
   *   For user-defined tools, they can be referenced with fully qualified name:
   * 
   *     ```
   *     tools:
   *       - name: my_library.my_tools.my_tool
   *     ```
   * 
   *   For tools that needs to be created via functions:
   * 
   *     ```
   *     tools:
   *       - name: my_library.my_tools.create_tool
   *         args:
   *           - name: param1
   *             value: value1
   *           - name: param2
   *             value: value2
   *     ```
   * 
   *   For more advanced tools, instead of specifying arguments in config, it's
   *   recommended to define them in Python files and reference them. E.g.,
   * 
   *     ```
   *     # tools.py
   *     my_mcp_toolset = McpToolset(
   *         connection_params=StdioServerParameters(
   *             command="npx",
   *             args=["-y", "@notionhq/notion-mcp-server"],
   *             env={"OPENAPI_MCP_HEADERS": NOTION_HEADERS},
   *         )
   *     )
   *     ```
   * 
   *   Then, reference the toolset in config:
   * 
   *   ```
   *   tools:
   *     - name: tools.my_mcp_toolset
   *   ```
   */
  tools(value: unknown): this {
    return this._setConfig("tools", value);
  }

  /**
   * Optional. LlmAgent.before_model_callbacks.
   * 
   * Example:
   * 
   *   ```
   *   before_model_callbacks:
   *     - name: my_library.callbacks.before_model_callback
   *   ```
   */
  beforeModelCallbacks(value: unknown): this {
    return this._setConfig("before_model_callbacks", value);
  }

  /**
   * Optional. LlmAgent.after_model_callbacks.
   */
  afterModelCallbacks(value: unknown): this {
    return this._setConfig("after_model_callbacks", value);
  }

  /**
   * Optional. LlmAgent.before_tool_callbacks.
   */
  beforeToolCallbacks(value: unknown): this {
    return this._setConfig("before_tool_callbacks", value);
  }

  /**
   * Optional. LlmAgent.after_tool_callbacks.
   */
  afterToolCallbacks(value: unknown): this {
    return this._setConfig("after_tool_callbacks", value);
  }

  /**
   * Optional. LlmAgent.generate_content_config.
   */
  generateContentConfig(value: unknown | undefined): this {
    return this._setConfig("generate_content_config", value);
  }

  /**
   * Append to ``sub_agents`` (lazy — built at .build() time).
   */
  subAgent(value: unknown): this {
    return this._addToList("sub_agents", value);
  }

  /**
   * Append to ``before_agent_callbacks`` (lazy — built at .build() time).
   */
  beforeAgentCallback(value: unknown): this {
    return this._addToList("before_agent_callbacks", value);
  }

  /**
   * Append to ``after_agent_callbacks`` (lazy — built at .build() time).
   */
  afterAgentCallback(value: unknown): this {
    return this._addToList("after_agent_callbacks", value);
  }

  /**
   * Append to ``tools`` (lazy — built at .build() time).
   */
  tool(value: unknown): this {
    return this._addToList("tools", value);
  }

  /**
   * Append to ``before_model_callbacks`` (lazy — built at .build() time).
   */
  beforeModelCallback(value: unknown): this {
    return this._addToList("before_model_callbacks", value);
  }

  /**
   * Append to ``after_model_callbacks`` (lazy — built at .build() time).
   */
  afterModelCallback(value: unknown): this {
    return this._addToList("after_model_callbacks", value);
  }

  /**
   * Append to ``before_tool_callbacks`` (lazy — built at .build() time).
   */
  beforeToolCallback(value: unknown): this {
    return this._addToList("before_tool_callbacks", value);
  }

  /**
   * Append to ``after_tool_callbacks`` (lazy — built at .build() time).
   */
  afterToolCallback(value: unknown): this {
    return this._addToList("after_tool_callbacks", value);
  }

  /**
   * The config for the YAML schema of a LlmAgent. Resolve into a native ADK _ADK_LlmAgentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("LlmAgentConfig");
  }
}

/**
 * The config for the YAML schema of a LoopAgent.
 */
export class LoopAgentConfig extends BuilderBase {
  constructor(name: string) {
    super(name);
  }

  /**
   * Set agent description (metadata for transfer routing and topology display — NOT sent to the LLM as instruction). Always set this on sub-agents so the coordinator LLM can pick the right specialist.
   */
  describe(value: string): this {
    return this._setConfig("description", value);
  }

  /**
   * The value is used to uniquely identify the LoopAgent class.
   */
  agentClass(value: string): this {
    return this._setConfig("agent_class", value);
  }

  /**
   * Optional. The sub-agents of the agent.
   */
  subAgents(value: unknown): this {
    return this._setConfig("sub_agents", value);
  }

  /**
   * Optional. The before_agent_callbacks of the agent.
   * 
   * Example:
   * 
   *   ```
   *   before_agent_callbacks:
   *     - name: my_library.security_callbacks.before_agent_callback
   *   ```
   */
  beforeAgentCallbacks(value: unknown): this {
    return this._setConfig("before_agent_callbacks", value);
  }

  /**
   * Optional. The after_agent_callbacks of the agent.
   */
  afterAgentCallbacks(value: unknown): this {
    return this._setConfig("after_agent_callbacks", value);
  }

  /**
   * Optional. LoopAgent.max_iterations.
   */
  maxIterations(value: number | undefined): this {
    return this._setConfig("max_iterations", value);
  }

  /**
   * Append to ``sub_agents`` (lazy — built at .build() time).
   */
  subAgent(value: unknown): this {
    return this._addToList("sub_agents", value);
  }

  /**
   * Append to ``before_agent_callbacks`` (lazy — built at .build() time).
   */
  beforeAgentCallback(value: unknown): this {
    return this._addToList("before_agent_callbacks", value);
  }

  /**
   * Append to ``after_agent_callbacks`` (lazy — built at .build() time).
   */
  afterAgentCallback(value: unknown): this {
    return this._addToList("after_agent_callbacks", value);
  }

  /**
   * The config for the YAML schema of a LoopAgent. Resolve into a native ADK _ADK_LoopAgentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("LoopAgentConfig");
  }
}

/**
 * The config for the YAML schema of a ParallelAgent.
 */
export class ParallelAgentConfig extends BuilderBase {
  constructor(name: string) {
    super(name);
  }

  /**
   * Set agent description (metadata for transfer routing and topology display — NOT sent to the LLM as instruction). Always set this on sub-agents so the coordinator LLM can pick the right specialist.
   */
  describe(value: string): this {
    return this._setConfig("description", value);
  }

  /**
   * The value is used to uniquely identify the ParallelAgent class.
   */
  agentClass(value: string): this {
    return this._setConfig("agent_class", value);
  }

  /**
   * Optional. The sub-agents of the agent.
   */
  subAgents(value: unknown): this {
    return this._setConfig("sub_agents", value);
  }

  /**
   * Optional. The before_agent_callbacks of the agent.
   * 
   * Example:
   * 
   *   ```
   *   before_agent_callbacks:
   *     - name: my_library.security_callbacks.before_agent_callback
   *   ```
   */
  beforeAgentCallbacks(value: unknown): this {
    return this._setConfig("before_agent_callbacks", value);
  }

  /**
   * Optional. The after_agent_callbacks of the agent.
   */
  afterAgentCallbacks(value: unknown): this {
    return this._setConfig("after_agent_callbacks", value);
  }

  /**
   * Append to ``sub_agents`` (lazy — built at .build() time).
   */
  subAgent(value: unknown): this {
    return this._addToList("sub_agents", value);
  }

  /**
   * Append to ``before_agent_callbacks`` (lazy — built at .build() time).
   */
  beforeAgentCallback(value: unknown): this {
    return this._addToList("before_agent_callbacks", value);
  }

  /**
   * Append to ``after_agent_callbacks`` (lazy — built at .build() time).
   */
  afterAgentCallback(value: unknown): this {
    return this._addToList("after_agent_callbacks", value);
  }

  /**
   * The config for the YAML schema of a ParallelAgent. Resolve into a native ADK _ADK_ParallelAgentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ParallelAgentConfig");
  }
}

/**
 * Configs for runtime behavior of agents.
 */
export class RunConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the `input_audio_transcription` field.
   */
  inputAudioTranscribe(value: unknown | undefined): this {
    return this._setConfig("input_audio_transcription", value);
  }

  /**
   * Set the `output_audio_transcription` field.
   */
  outputAudioTranscribe(value: unknown | undefined): this {
    return this._setConfig("output_audio_transcription", value);
  }

  /**
   * Set the ``speech_config`` field.
   */
  speechConfig(value: unknown | undefined): this {
    return this._setConfig("speech_config", value);
  }

  /**
   * Set the ``response_modalities`` field.
   */
  responseModalities(value: unknown): this {
    return this._setConfig("response_modalities", value);
  }

  /**
   * Whether or not to save the input blobs as artifacts. DEPRECATED: Use SaveFilesAsArtifactsPlugin instead for better control and flexibility. See google.adk.plugins.SaveFilesAsArtifactsPlugin.
   */
  saveInputBlobsAsArtifacts(value: boolean): this {
    return this._setConfig("save_input_blobs_as_artifacts", value);
  }

  /**
   * Set the ``support_cfc`` field.
   */
  supportCfc(value: boolean): this {
    return this._setConfig("support_cfc", value);
  }

  /**
   * Set the ``streaming_mode`` field.
   */
  streamingMode(value: unknown): this {
    return this._setConfig("streaming_mode", value);
  }

  /**
   * Set the ``realtime_input_config`` field.
   */
  realtimeInputConfig(value: unknown | undefined): this {
    return this._setConfig("realtime_input_config", value);
  }

  /**
   * Set the ``enable_affective_dialog`` field.
   */
  enableAffectiveDialog(value: boolean | undefined): this {
    return this._setConfig("enable_affective_dialog", value);
  }

  /**
   * Set the ``proactivity`` field.
   */
  proactivity(value: unknown | undefined): this {
    return this._setConfig("proactivity", value);
  }

  /**
   * Set the ``session_resumption`` field.
   */
  sessionResumption(value: unknown | undefined): this {
    return this._setConfig("session_resumption", value);
  }

  /**
   * Set the ``context_window_compression`` field.
   */
  contextWindowCompression(value: unknown | undefined): this {
    return this._setConfig("context_window_compression", value);
  }

  /**
   * Set the ``save_live_blob`` field.
   */
  saveLiveBlob(value: boolean): this {
    return this._setConfig("save_live_blob", value);
  }

  /**
   * Set the ``tool_thread_pool_config`` field.
   */
  toolThreadPoolConfig(value: unknown | undefined): this {
    return this._setConfig("tool_thread_pool_config", value);
  }

  /**
   * DEPRECATED: Use save_live_blob instead. If set to True, it saves live video and audio data to session and artifact service.
   */
  saveLiveAudio(value: boolean): this {
    return this._setConfig("save_live_audio", value);
  }

  /**
   * Set the ``max_llm_calls`` field.
   */
  maxLlmCalls(value: number): this {
    return this._setConfig("max_llm_calls", value);
  }

  /**
   * Set the ``custom_metadata`` field.
   */
  customMetadata(value: unknown): this {
    return this._setConfig("custom_metadata", value);
  }

  /**
   * Configs for runtime behavior of agents. Resolve into a native ADK _ADK_RunConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("RunConfig");
  }
}

/**
 * Configuration for the tool thread pool executor.
 */
export class ToolThreadPoolConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Maximum number of worker threads in the pool.
   */
  maxWorkers(value: number): this {
    return this._setConfig("max_workers", value);
  }

  /**
   * Configuration for the tool thread pool executor. Resolve into a native ADK _ADK_ToolThreadPoolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ToolThreadPoolConfig");
  }
}

/**
 * The config for the YAML schema of a SequentialAgent.
 */
export class SequentialAgentConfig extends BuilderBase {
  constructor(name: string) {
    super(name);
  }

  /**
   * Set agent description (metadata for transfer routing and topology display — NOT sent to the LLM as instruction). Always set this on sub-agents so the coordinator LLM can pick the right specialist.
   */
  describe(value: string): this {
    return this._setConfig("description", value);
  }

  /**
   * The value is used to uniquely identify the SequentialAgent class.
   */
  agentClass(value: string): this {
    return this._setConfig("agent_class", value);
  }

  /**
   * Optional. The sub-agents of the agent.
   */
  subAgents(value: unknown): this {
    return this._setConfig("sub_agents", value);
  }

  /**
   * Optional. The before_agent_callbacks of the agent.
   * 
   * Example:
   * 
   *   ```
   *   before_agent_callbacks:
   *     - name: my_library.security_callbacks.before_agent_callback
   *   ```
   */
  beforeAgentCallbacks(value: unknown): this {
    return this._setConfig("before_agent_callbacks", value);
  }

  /**
   * Optional. The after_agent_callbacks of the agent.
   */
  afterAgentCallbacks(value: unknown): this {
    return this._setConfig("after_agent_callbacks", value);
  }

  /**
   * Append to ``sub_agents`` (lazy — built at .build() time).
   */
  subAgent(value: unknown): this {
    return this._addToList("sub_agents", value);
  }

  /**
   * Append to ``before_agent_callbacks`` (lazy — built at .build() time).
   */
  beforeAgentCallback(value: unknown): this {
    return this._addToList("before_agent_callbacks", value);
  }

  /**
   * Append to ``after_agent_callbacks`` (lazy — built at .build() time).
   */
  afterAgentCallback(value: unknown): this {
    return this._addToList("after_agent_callbacks", value);
  }

  /**
   * The config for the YAML schema of a SequentialAgent. Resolve into a native ADK _ADK_SequentialAgentConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("SequentialAgentConfig");
  }
}

/**
 * The config of event compaction for an application.
 */
export class EventsCompactionConfig extends BuilderBase {
  constructor(compaction_interval: string, overlap_size: string) {
    super(compaction_interval);
    this._config.set("overlap_size", overlap_size);
  }

  /**
   * Set the ``summarizer`` field.
   */
  summarizer(value: unknown | undefined): this {
    return this._setConfig("summarizer", value);
  }

  /**
   * Set the ``token_threshold`` field.
   */
  tokenThreshold(value: number | undefined): this {
    return this._setConfig("token_threshold", value);
  }

  /**
   * Set the ``event_retention_size`` field.
   */
  eventRetentionSize(value: number | undefined): this {
    return this._setConfig("event_retention_size", value);
  }

  /**
   * The config of event compaction for an application. Resolve into a native ADK _ADK_EventsCompactionConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("EventsCompactionConfig");
  }
}

/**
 * The config of the resumability for an application.
 */
export class ResumabilityConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``is_resumable`` field.
   */
  isResumable(value: boolean): this {
    return this._setConfig("is_resumable", value);
  }

  /**
   * The config of the resumability for an application. Resolve into a native ADK _ADK_ResumabilityConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ResumabilityConfig");
  }
}

/**
 * Feature configuration.
 */
export class FeatureConfig extends BuilderBase {
  constructor(stage: string) {
    super(stage);
  }

  /**
   * Set the ``default_on`` field.
   */
  defaultOn(value: boolean): this {
    return this._setConfig("default_on", value);
  }

  /**
   * Feature configuration. Resolve into a native ADK _ADK_FeatureConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("FeatureConfig");
  }
}

/**
 * Configuration for audio caching behavior.
 */
export class AudioCacheConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``max_cache_size_bytes`` field.
   */
  maxCacheSizeBytes(value: number): this {
    return this._setConfig("max_cache_size_bytes", value);
  }

  /**
   * Set the ``max_cache_duration_seconds`` field.
   */
  maxCacheDurationSeconds(value: number): this {
    return this._setConfig("max_cache_duration_seconds", value);
  }

  /**
   * Set the ``auto_flush_threshold`` field.
   */
  autoFlushThreshold(value: number): this {
    return this._setConfig("auto_flush_threshold", value);
  }

  /**
   * Configuration for audio caching behavior. Resolve into a native ADK _ADK_AudioCacheConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("AudioCacheConfig");
  }
}

/**
 * Configuration for the IterativePromptOptimizer.
 */
export class SimplePromptOptimizerConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * The configuration for the optimizer model.
   */
  modelConfigure(value: unknown): this {
    return this._setConfig("model_configuration", value);
  }

  /**
   * The model used to analyze the eval results and optimize the agent.
   */
  optimizerModel(value: string): this {
    return this._setConfig("optimizer_model", value);
  }

  /**
   * The number of optimization rounds to run.
   */
  numIterations(value: number): this {
    return this._setConfig("num_iterations", value);
  }

  /**
   * The number of training examples to use for scoring each candidate.
   */
  batchSize(value: number): this {
    return this._setConfig("batch_size", value);
  }

  /**
   * Configuration for the IterativePromptOptimizer. Resolve into a native ADK _ADK_SimplePromptOptimizerConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("SimplePromptOptimizerConfig");
  }
}

/**
 * Configuration for the BigQueryAgentAnalyticsPlugin.
 */
export class BigQueryLoggerConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``enabled`` field.
   */
  enabled(value: boolean): this {
    return this._setConfig("enabled", value);
  }

  /**
   * Set the ``event_allowlist`` field.
   */
  eventAllowlist(value: unknown): this {
    return this._setConfig("event_allowlist", value);
  }

  /**
   * Set the ``event_denylist`` field.
   */
  eventDenylist(value: unknown): this {
    return this._setConfig("event_denylist", value);
  }

  /**
   * Set the ``max_content_length`` field.
   */
  maxContentLength(value: number): this {
    return this._setConfig("max_content_length", value);
  }

  /**
   * Set the ``table_id`` field.
   */
  tableId(value: string): this {
    return this._setConfig("table_id", value);
  }

  /**
   * Set the ``clustering_fields`` field.
   */
  clusteringFields(value: unknown[]): this {
    return this._setConfig("clustering_fields", value);
  }

  /**
   * Set the ``log_multi_modal_content`` field.
   */
  logMultiModalContent(value: boolean): this {
    return this._setConfig("log_multi_modal_content", value);
  }

  /**
   * Set the ``retry_config`` field.
   */
  retryConfig(value: unknown): this {
    return this._setConfig("retry_config", value);
  }

  /**
   * Set the ``batch_size`` field.
   */
  batchSize(value: number): this {
    return this._setConfig("batch_size", value);
  }

  /**
   * Set the ``batch_flush_interval`` field.
   */
  batchFlushInterval(value: number): this {
    return this._setConfig("batch_flush_interval", value);
  }

  /**
   * Set the ``shutdown_timeout`` field.
   */
  shutdownTimeout(value: number): this {
    return this._setConfig("shutdown_timeout", value);
  }

  /**
   * Set the ``queue_max_size`` field.
   */
  queueMaxSize(value: number): this {
    return this._setConfig("queue_max_size", value);
  }

  /**
   * Set the ``content_formatter`` field.
   */
  contentFormatter(value: (...args: unknown[]) => unknown): this {
    return this._setConfig("content_formatter", value);
  }

  /**
   * Set the ``gcs_bucket_name`` field.
   */
  gcsBucketName(value: string | undefined): this {
    return this._setConfig("gcs_bucket_name", value);
  }

  /**
   * Set the ``connection_id`` field.
   */
  connectionId(value: string | undefined): this {
    return this._setConfig("connection_id", value);
  }

  /**
   * Set the ``log_session_metadata`` field.
   */
  logSessionMetadata(value: boolean): this {
    return this._setConfig("log_session_metadata", value);
  }

  /**
   * Set the ``custom_tags`` field.
   */
  customTags(value: Record<string, unknown>): this {
    return this._setConfig("custom_tags", value);
  }

  /**
   * Configuration for the BigQueryAgentAnalyticsPlugin. Resolve into a native ADK _ADK_BigQueryLoggerConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BigQueryLoggerConfig");
  }
}

/**
 * Configuration for retrying failed BigQuery write operations.
 */
export class RetryConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``max_retries`` field.
   */
  maxRetries(value: number): this {
    return this._setConfig("max_retries", value);
  }

  /**
   * Set the ``initial_delay`` field.
   */
  initialDelay(value: number): this {
    return this._setConfig("initial_delay", value);
  }

  /**
   * Set the ``multiplier`` field.
   */
  multiplier(value: number): this {
    return this._setConfig("multiplier", value);
  }

  /**
   * Set the ``max_delay`` field.
   */
  maxDelay(value: number): this {
    return this._setConfig("max_delay", value);
  }

  /**
   * Configuration for retrying failed BigQuery write operations. Resolve into a native ADK _ADK_RetryConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("RetryConfig");
  }
}

/**
 * The configuration of getting a session.
 */
export class GetSessionConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``num_recent_events`` field.
   */
  numRecentEvents(value: number | undefined): this {
    return this._setConfig("num_recent_events", value);
  }

  /**
   * Set the ``after_timestamp`` field.
   */
  afterTimestamp(value: number | undefined): this {
    return this._setConfig("after_timestamp", value);
  }

  /**
   * The configuration of getting a session. Resolve into a native ADK _ADK_GetSessionConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("GetSessionConfig");
  }
}

/**
 * Base Google Credentials Configuration for Google API tools (Experimental).
 */
export class BaseGoogleCredentialsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``credentials`` field.
   */
  credentials(value: unknown | undefined): this {
    return this._setConfig("credentials", value);
  }

  /**
   * Set the ``external_access_token_key`` field.
   */
  externalAccessTokenKey(value: string | undefined): this {
    return this._setConfig("external_access_token_key", value);
  }

  /**
   * Set the ``client_id`` field.
   */
  clientId(value: string | undefined): this {
    return this._setConfig("client_id", value);
  }

  /**
   * Set the ``client_secret`` field.
   */
  clientSecret(value: string | undefined): this {
    return this._setConfig("client_secret", value);
  }

  /**
   * Set the ``scopes`` field.
   */
  scopes(value: unknown): this {
    return this._setConfig("scopes", value);
  }

  /**
   * Base Google Credentials Configuration for Google API tools (Experimental). Resolve into a native ADK _ADK_BaseGoogleCredentialsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BaseGoogleCredentialsConfig");
  }
}

/**
 * Configuration for AgentSimulator.
 */
export class AgentSimulatorConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the `simulation_model_configuration` field.
   */
  simulationModelConfigure(value: unknown): this {
    return this._setConfig("simulation_model_configuration", value);
  }

  /**
   * Set the ``tool_simulation_configs`` field.
   */
  toolSimulationConfigs(value: unknown[]): this {
    return this._setConfig("tool_simulation_configs", value);
  }

  /**
   * Set the ``simulation_model`` field.
   */
  simulationModel(value: string): this {
    return this._setConfig("simulation_model", value);
  }

  /**
   * Set the ``tracing_path`` field.
   */
  tracingPath(value: string | undefined): this {
    return this._setConfig("tracing_path", value);
  }

  /**
   * Set the ``environment_data`` field.
   */
  environmentData(value: string | undefined): this {
    return this._setConfig("environment_data", value);
  }

  /**
   * Append to ``tool_simulation_configs`` (lazy — built at .build() time).
   */
  toolSimulationConfig(value: unknown): this {
    return this._addToList("tool_simulation_configs", value);
  }

  /**
   * Configuration for AgentSimulator. Resolve into a native ADK _ADK_AgentSimulatorConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("AgentSimulatorConfig");
  }
}

/**
 * Injection configuration for a tool.
 */
export class InjectionConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``injection_probability`` field.
   */
  injectionProbability(value: number): this {
    return this._setConfig("injection_probability", value);
  }

  /**
   * Set the ``match_args`` field.
   */
  matchArgs(value: unknown): this {
    return this._setConfig("match_args", value);
  }

  /**
   * Set the ``injected_latency_seconds`` field.
   */
  injectedLatencySeconds(value: number): this {
    return this._setConfig("injected_latency_seconds", value);
  }

  /**
   * Set the ``random_seed`` field.
   */
  randomSeed(value: number | undefined): this {
    return this._setConfig("random_seed", value);
  }

  /**
   * Set the ``injected_error`` field.
   */
  injectedError(value: unknown | undefined): this {
    return this._setConfig("injected_error", value);
  }

  /**
   * Set the ``injected_response`` field.
   */
  injectedResponse(value: unknown): this {
    return this._setConfig("injected_response", value);
  }

  /**
   * Injection configuration for a tool. Resolve into a native ADK _ADK_InjectionConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("InjectionConfig");
  }
}

/**
 * Simulation configuration for a single tool.
 */
export class ToolSimulationConfig extends BuilderBase {
  constructor(tool_name: string) {
    super(tool_name);
  }

  /**
   * Set the ``injection_configs`` field.
   */
  injectionConfigs(value: unknown[]): this {
    return this._setConfig("injection_configs", value);
  }

  /**
   * Set the ``mock_strategy_type`` field.
   */
  mockStrategyType(value: unknown): this {
    return this._setConfig("mock_strategy_type", value);
  }

  /**
   * Append to ``injection_configs`` (lazy — built at .build() time).
   */
  injectionConfig(value: unknown): this {
    return this._addToList("injection_configs", value);
  }

  /**
   * Simulation configuration for a single tool. Resolve into a native ADK _ADK_ToolSimulationConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ToolSimulationConfig");
  }
}

/**
 * The config for the AgentTool.
 */
export class AgentToolConfig extends BuilderBase {
  constructor(agent: string) {
    super(agent);
  }

  /**
   * Set the `skip_summarization` field.
   */
  skipSummarizate(value: boolean): this {
    return this._setConfig("skip_summarization", value);
  }

  /**
   * Set the ``include_plugins`` field.
   */
  includePlugins(value: boolean): this {
    return this._setConfig("include_plugins", value);
  }

  /**
   * The config for the AgentTool. Resolve into a native ADK _ADK_AgentToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("AgentToolConfig");
  }
}

/**
 * BigQuery Credentials Configuration for Google API tools (Experimental).
 */
export class BigQueryCredentialsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``credentials`` field.
   */
  credentials(value: unknown | undefined): this {
    return this._setConfig("credentials", value);
  }

  /**
   * Set the ``external_access_token_key`` field.
   */
  externalAccessTokenKey(value: string | undefined): this {
    return this._setConfig("external_access_token_key", value);
  }

  /**
   * Set the ``client_id`` field.
   */
  clientId(value: string | undefined): this {
    return this._setConfig("client_id", value);
  }

  /**
   * Set the ``client_secret`` field.
   */
  clientSecret(value: string | undefined): this {
    return this._setConfig("client_secret", value);
  }

  /**
   * Set the ``scopes`` field.
   */
  scopes(value: unknown): this {
    return this._setConfig("scopes", value);
  }

  /**
   * BigQuery Credentials Configuration for Google API tools (Experimental). Resolve into a native ADK _ADK_BigQueryCredentialsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BigQueryCredentialsConfig");
  }
}

/**
 * Configuration for BigQuery tools.
 */
export class BigQueryToolConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the `location` field.
   */
  locate(value: string | undefined): this {
    return this._setConfig("location", value);
  }

  /**
   * Set the ``write_mode`` field.
   */
  writeMode(value: unknown): this {
    return this._setConfig("write_mode", value);
  }

  /**
   * Set the ``maximum_bytes_billed`` field.
   */
  maximumBytesBilled(value: number | undefined): this {
    return this._setConfig("maximum_bytes_billed", value);
  }

  /**
   * Set the ``max_query_result_rows`` field.
   */
  maxQueryResultRows(value: number): this {
    return this._setConfig("max_query_result_rows", value);
  }

  /**
   * Set the ``application_name`` field.
   */
  applicationName(value: string | undefined): this {
    return this._setConfig("application_name", value);
  }

  /**
   * Set the ``compute_project_id`` field.
   */
  computeProjectId(value: string | undefined): this {
    return this._setConfig("compute_project_id", value);
  }

  /**
   * Set the ``job_labels`` field.
   */
  jobLabels(value: unknown): this {
    return this._setConfig("job_labels", value);
  }

  /**
   * Configuration for BigQuery tools. Resolve into a native ADK _ADK_BigQueryToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BigQueryToolConfig");
  }
}

/**
 * Bigtable Credentials Configuration for Google API tools (Experimental).
 */
export class BigtableCredentialsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``credentials`` field.
   */
  credentials(value: unknown | undefined): this {
    return this._setConfig("credentials", value);
  }

  /**
   * Set the ``external_access_token_key`` field.
   */
  externalAccessTokenKey(value: string | undefined): this {
    return this._setConfig("external_access_token_key", value);
  }

  /**
   * Set the ``client_id`` field.
   */
  clientId(value: string | undefined): this {
    return this._setConfig("client_id", value);
  }

  /**
   * Set the ``client_secret`` field.
   */
  clientSecret(value: string | undefined): this {
    return this._setConfig("client_secret", value);
  }

  /**
   * Set the ``scopes`` field.
   */
  scopes(value: unknown): this {
    return this._setConfig("scopes", value);
  }

  /**
   * Bigtable Credentials Configuration for Google API tools (Experimental). Resolve into a native ADK _ADK_BigtableCredentialsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BigtableCredentialsConfig");
  }
}

/**
 * Configuration for Data Agent tools.
 */
export class DataAgentToolConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``max_query_result_rows`` field.
   */
  maxQueryResultRows(value: number): this {
    return this._setConfig("max_query_result_rows", value);
  }

  /**
   * Configuration for Data Agent tools. Resolve into a native ADK _ADK_DataAgentToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("DataAgentToolConfig");
  }
}

/**
 * Data Agent Credentials Configuration for Google API tools.
 */
export class DataAgentCredentialsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``credentials`` field.
   */
  credentials(value: unknown | undefined): this {
    return this._setConfig("credentials", value);
  }

  /**
   * Set the ``external_access_token_key`` field.
   */
  externalAccessTokenKey(value: string | undefined): this {
    return this._setConfig("external_access_token_key", value);
  }

  /**
   * Set the ``client_id`` field.
   */
  clientId(value: string | undefined): this {
    return this._setConfig("client_id", value);
  }

  /**
   * Set the ``client_secret`` field.
   */
  clientSecret(value: string | undefined): this {
    return this._setConfig("client_secret", value);
  }

  /**
   * Set the ``scopes`` field.
   */
  scopes(value: unknown): this {
    return this._setConfig("scopes", value);
  }

  /**
   * Data Agent Credentials Configuration for Google API tools. Resolve into a native ADK _ADK_DataAgentCredentialsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("DataAgentCredentialsConfig");
  }
}

/**
 * Fluent builder for ExampleToolConfig.
 */
export class ExampleToolConfig extends BuilderBase {
  constructor(examples: string) {
    super(examples);
  }

  /**
   * Fluent builder for ExampleToolConfig. Resolve into a native ADK _ADK_ExampleToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ExampleToolConfig");
  }
}

/**
 * The config for McpToolset.
 */
export class McpToolsetConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``stdio_server_params`` field.
   */
  stdioServerParams(value: unknown | undefined): this {
    return this._setConfig("stdio_server_params", value);
  }

  /**
   * Set the ``stdio_connection_params`` field.
   */
  stdioConnectionParams(value: unknown | undefined): this {
    return this._setConfig("stdio_connection_params", value);
  }

  /**
   * Set the ``sse_connection_params`` field.
   */
  sseConnectionParams(value: unknown | undefined): this {
    return this._setConfig("sse_connection_params", value);
  }

  /**
   * Set the ``streamable_http_connection_params`` field.
   */
  streamableHttpConnectionParams(value: unknown | undefined): this {
    return this._setConfig("streamable_http_connection_params", value);
  }

  /**
   * Set the ``tool_filter`` field.
   */
  toolFilter(value: unknown): this {
    return this._setConfig("tool_filter", value);
  }

  /**
   * Set the ``tool_name_prefix`` field.
   */
  toolNamePrefix(value: string | undefined): this {
    return this._setConfig("tool_name_prefix", value);
  }

  /**
   * Set the ``auth_scheme`` field.
   */
  authScheme(value: unknown | unknown | unknown | unknown | unknown | unknown | undefined): this {
    return this._setConfig("auth_scheme", value);
  }

  /**
   * Set the ``auth_credential`` field.
   */
  authCredential(value: unknown | undefined): this {
    return this._setConfig("auth_credential", value);
  }

  /**
   * Set the ``use_mcp_resources`` field.
   */
  useMcpResources(value: boolean): this {
    return this._setConfig("use_mcp_resources", value);
  }

  /**
   * The config for McpToolset. Resolve into a native ADK _ADK_McpToolsetConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("McpToolsetConfig");
  }
}

/**
 * Configuration for Pub/Sub tools.
 */
export class PubSubToolConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``project_id`` field.
   */
  projectId(value: string | undefined): this {
    return this._setConfig("project_id", value);
  }

  /**
   * Configuration for Pub/Sub tools. Resolve into a native ADK _ADK_PubSubToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("PubSubToolConfig");
  }
}

/**
 * Pub/Sub Credentials Configuration for Google API tools (Experimental).
 */
export class PubSubCredentialsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``credentials`` field.
   */
  credentials(value: unknown | undefined): this {
    return this._setConfig("credentials", value);
  }

  /**
   * Set the ``external_access_token_key`` field.
   */
  externalAccessTokenKey(value: string | undefined): this {
    return this._setConfig("external_access_token_key", value);
  }

  /**
   * Set the ``client_id`` field.
   */
  clientId(value: string | undefined): this {
    return this._setConfig("client_id", value);
  }

  /**
   * Set the ``client_secret`` field.
   */
  clientSecret(value: string | undefined): this {
    return this._setConfig("client_secret", value);
  }

  /**
   * Set the ``scopes`` field.
   */
  scopes(value: unknown): this {
    return this._setConfig("scopes", value);
  }

  /**
   * Pub/Sub Credentials Configuration for Google API tools (Experimental). Resolve into a native ADK _ADK_PubSubCredentialsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("PubSubCredentialsConfig");
  }
}

/**
 * Spanner Credentials Configuration for Google API tools (Experimental).
 */
export class SpannerCredentialsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Set the ``credentials`` field.
   */
  credentials(value: unknown | undefined): this {
    return this._setConfig("credentials", value);
  }

  /**
   * Set the ``external_access_token_key`` field.
   */
  externalAccessTokenKey(value: string | undefined): this {
    return this._setConfig("external_access_token_key", value);
  }

  /**
   * Set the ``client_id`` field.
   */
  clientId(value: string | undefined): this {
    return this._setConfig("client_id", value);
  }

  /**
   * Set the ``client_secret`` field.
   */
  clientSecret(value: string | undefined): this {
    return this._setConfig("client_secret", value);
  }

  /**
   * Set the ``scopes`` field.
   */
  scopes(value: unknown): this {
    return this._setConfig("scopes", value);
  }

  /**
   * Spanner Credentials Configuration for Google API tools (Experimental). Resolve into a native ADK _ADK_SpannerCredentialsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("SpannerCredentialsConfig");
  }
}

/**
 * The base class for all tool configs.
 */
export class BaseToolConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * The base class for all tool configs. Resolve into a native ADK _ADK_BaseToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("BaseToolConfig");
  }
}

/**
 * Config to host free key-value pairs for the args in ToolConfig.
 */
export class ToolArgsConfig extends BuilderBase {
  constructor() {
    super("");
  }

  /**
   * Config to host free key-value pairs for the args in ToolConfig. Resolve into a native ADK _ADK_ToolArgsConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ToolArgsConfig");
  }
}

/**
 * The configuration for a tool.
 */
export class ToolConfig extends BuilderBase {
  constructor(name: string) {
    super(name);
  }

  /**
   * The args for the tool.
   */
  args(value: unknown | undefined): this {
    return this._setConfig("args", value);
  }

  /**
   * The configuration for a tool. Resolve into a native ADK _ADK_ToolConfig.
   */
  build(): Record<string, unknown> {
    return this._buildConfig("ToolConfig");
  }
}
