"""Type stubs for BuilderBase mixin and module-level primitives."""

from collections.abc import Callable
from typing import Any, Self

# ======================================================================
# Exceptions (re-exported from _exceptions)
# ======================================================================

class ADKFluentError(Exception): ...

class BuilderError(ADKFluentError):
    name: str
    builder_type: str
    field_errors: list[str]
    original: Exception | None
    def __init__(
        self,
        name: str,
        builder_type: str,
        field_errors: list[str],
        original: Exception | None = None,
    ) -> None: ...

# ======================================================================
# Primitive runtime agents (re-exported from _primitives)
# ======================================================================

class FnAgent: ...
class TapAgent: ...
class CaptureAgent: ...
class FallbackAgent: ...
class MapOverAgent: ...
class TimeoutAgent: ...
class GateAgent: ...
class RaceAgent: ...
class DispatchAgent: ...
class JoinAgent: ...

def get_execution_mode() -> str: ...

# ======================================================================
# Primitive builder bases and builders (re-exported from _primitive_builders)
# ======================================================================

class PrimitiveBuilderBase(BuilderBase): ...

class TimedAgent(PrimitiveBuilderBase):
    def __init__(
        self,
        name: str,
        *,
        _agent: Any = None,
        _seconds: float = 30.0,
    ) -> None: ...
    def build(self) -> Any: ...

class BackgroundTask(PrimitiveBuilderBase):
    def __init__(
        self,
        name: str,
        *,
        _agents: list[Any] | None = None,
        _task_names: tuple[str, ...] | None = None,
        _on_complete: Callable | None = None,
        _on_error: Callable | None = None,
        _stream_to: str | None = None,
        _max_tasks: int | None = None,
    ) -> None: ...
    def build(self) -> Any: ...

# ======================================================================
# _UntilSpec and until()
# ======================================================================

class _UntilSpec:
    predicate: Callable
    max: int
    def __init__(self, predicate: Callable, *, max: int = 10) -> None: ...
    def __repr__(self) -> str: ...

def until(predicate: Callable, *, max: int = 10) -> _UntilSpec: ...

# ======================================================================
# Module-level expression primitives (re-exported from _primitive_builders)
# ======================================================================

def tap(fn: Callable) -> Any: ...
def expect(predicate: Callable, *, msg: str = ...) -> Any: ...
def map_over(key: str) -> Any: ...
def gate(predicate: Callable) -> Any: ...
def race(*agents: Any) -> Any: ...
def dispatch(
    *agents: Any,
    name: str | None = None,
    on_complete: Callable | None = None,
    on_error: Callable | None = None,
    stream_to: str | None = None,
    max_tasks: int | None = None,
) -> Any: ...
def join(*, names: tuple[str, ...] | None = None) -> Any: ...

# ======================================================================
# BuilderBase
# ======================================================================

class BuilderBase:
    """Mixin base class providing shared builder capabilities."""

    _ALIASES: dict[str, str]
    _CALLBACK_ALIASES: dict[str, str]
    _ADDITIVE_FIELDS: set[str]
    _ADK_TARGET_CLASS: type | None
    _KNOWN_PARAMS: set[str] | None

    _config: dict[str, Any]
    _callbacks: dict[str, list[Callable]]
    _lists: dict[str, list]

    # ------------------------------------------------------------------
    # Build
    # ------------------------------------------------------------------

    def build(self) -> Any: ...

    # ------------------------------------------------------------------
    # Operator composition
    # ------------------------------------------------------------------

    def __rshift__(self, other: Any) -> BuilderBase: ...
    def __rrshift__(self, other: Any) -> BuilderBase: ...
    def __or__(self, other: BuilderBase) -> BuilderBase: ...
    def __mul__(self, other: int | _UntilSpec) -> BuilderBase: ...
    def __rmul__(self, iterations: int) -> BuilderBase: ...
    def __matmul__(self, schema: type) -> BuilderBase: ...
    def __floordiv__(self, other: Any) -> BuilderBase: ...

    # ------------------------------------------------------------------
    # Repr / dir
    # ------------------------------------------------------------------

    def __repr__(self) -> str: ...
    def __dir__(self) -> list[str]: ...
    @staticmethod
    def _format_value(v: Any) -> str: ...

    # ------------------------------------------------------------------
    # Validation and introspection
    # ------------------------------------------------------------------

    def validate(self) -> Self: ...
    def explain(
        self,
        *,
        format: str = "text",
        docs_url: str | None = None,
        open_browser: bool = False,
    ) -> str | dict: ...
    def inspect(self) -> str: ...

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]: ...
    def to_yaml(self) -> str: ...

    # ------------------------------------------------------------------
    # Cloning and immutability
    # ------------------------------------------------------------------

    def clone(self, new_name: str) -> Self: ...
    def with_(self, **overrides: Any) -> Self: ...

    # ------------------------------------------------------------------
    # Native / escape hatch
    # ------------------------------------------------------------------

    def native(self, fn: Callable) -> Self: ...
    def with_raw_config(self, **kwargs: Any) -> Self: ...

    # ------------------------------------------------------------------
    # Data flow
    # ------------------------------------------------------------------

    def reads(self, *keys: str) -> Self: ...
    def writes(self, key: str) -> Self: ...
    def accepts(self, schema: type) -> Self: ...
    def returns(self, schema: type) -> Self: ...
    def output(self, schema: type) -> Self: ...
    def produces(self, schema: type) -> Self: ...
    def consumes(self, schema: type) -> Self: ...
    def inject(self, **resources: Any) -> Self: ...

    # ------------------------------------------------------------------
    # Control flow
    # ------------------------------------------------------------------

    def prepend(self, fn: Callable) -> Self: ...
    def proceed_if(self, predicate: Callable) -> Self: ...
    def loop_until(self, predicate: Callable, *, max_iterations: int = 10) -> BuilderBase: ...
    def loop_while(self, predicate: Callable, *, max_iterations: int = 3) -> BuilderBase: ...
    def until(self, predicate: Callable) -> BuilderBase: ...
    def timeout(self, seconds: float) -> BuilderBase: ...
    def dispatch(
        self,
        *,
        name: str | None = None,
        on_complete: Callable | None = None,
        on_error: Callable | None = None,
        stream_to: str | None = None,
        progress_key: str | None = None,
    ) -> BuilderBase: ...

    # ------------------------------------------------------------------
    # Observation / testing
    # ------------------------------------------------------------------

    def tap(self, fn: Callable) -> BuilderBase: ...
    def mock(self, responses: list[str] | Callable) -> Self: ...
    def debug(self, enabled: bool = True) -> Self: ...

    # ------------------------------------------------------------------
    # Presets and middleware
    # ------------------------------------------------------------------

    def use(self, preset: Any) -> Self: ...
    def middleware(self, mw: Any) -> Self: ...
    def engine(self, name: str, **kwargs: Any) -> Self: ...
    def compute(self, config: Any) -> Self: ...

    # ------------------------------------------------------------------
    # Contract checking
    # ------------------------------------------------------------------

    def strict(self) -> Self: ...
    def unchecked(self) -> Self: ...

    # ------------------------------------------------------------------
    # Visibility policies
    # ------------------------------------------------------------------

    def transparent(self) -> Self: ...
    def filtered(self) -> Self: ...
    def annotated(self) -> Self: ...

    # ------------------------------------------------------------------
    # IR / visualization / diagnosis
    # ------------------------------------------------------------------

    def to_ir(self) -> Any: ...
    def to_app(self, config: Any = None) -> Any: ...
    def to_mermaid(
        self,
        *,
        show_contracts: bool = True,
        show_data_flow: bool = True,
        show_context: bool = False,
    ) -> str: ...
    def to_sequence_diagram(
        self,
        *,
        show_data_flow: bool = True,
        show_context: bool = True,
    ) -> str: ...
    def diagnose(self) -> Any: ...
    def doctor(self) -> str: ...
    def data_flow(self) -> Any: ...
    def data_flow_contract(self) -> Any: ...
    def infer_data_flow(self) -> Any: ...
    def auto_wire(self) -> Self: ...
    def wired(self) -> Self: ...
    def llm_anatomy(self) -> str: ...
