# AUTO-GENERATED by adk-fluent generator — do not edit manually
# Generated from google-adk 1.25.0
# Timestamp: 2026-02-20T05:19:42.477676+00:00

from collections.abc import AsyncGenerator, Callable
from typing import Any, Self

from google.adk.agents.agent_config import AgentConfig as _ADK_AgentConfig
from google.adk.agents.base_agent_config import BaseAgentConfig as _ADK_BaseAgentConfig
from google.adk.agents.common_configs import AgentRefConfig as _ADK_AgentRefConfig
from google.adk.agents.common_configs import ArgumentConfig as _ADK_ArgumentConfig
from google.adk.agents.common_configs import CodeConfig as _ADK_CodeConfig
from google.adk.agents.context_cache_config import ContextCacheConfig as _ADK_ContextCacheConfig
from google.adk.agents.llm_agent_config import LlmAgentConfig as _ADK_LlmAgentConfig
from google.adk.agents.loop_agent_config import LoopAgentConfig as _ADK_LoopAgentConfig
from google.adk.agents.parallel_agent_config import ParallelAgentConfig as _ADK_ParallelAgentConfig
from google.adk.agents.run_config import RunConfig as _ADK_RunConfig
from google.adk.agents.run_config import ToolThreadPoolConfig as _ADK_ToolThreadPoolConfig
from google.adk.agents.sequential_agent_config import SequentialAgentConfig as _ADK_SequentialAgentConfig
from google.adk.apps.app import EventsCompactionConfig as _ADK_EventsCompactionConfig
from google.adk.apps.app import ResumabilityConfig as _ADK_ResumabilityConfig
from google.adk.features._feature_registry import FeatureConfig as _ADK_FeatureConfig
from google.adk.flows.llm_flows.audio_cache_manager import AudioCacheConfig as _ADK_AudioCacheConfig
from google.adk.optimization.simple_prompt_optimizer import SimplePromptOptimizerConfig as _ADK_SimplePromptOptimizerConfig
from google.adk.plugins.bigquery_agent_analytics_plugin import BigQueryLoggerConfig as _ADK_BigQueryLoggerConfig
from google.adk.plugins.bigquery_agent_analytics_plugin import RetryConfig as _ADK_RetryConfig
from google.adk.sessions.base_session_service import GetSessionConfig as _ADK_GetSessionConfig
from google.adk.tools._google_credentials import BaseGoogleCredentialsConfig as _ADK_BaseGoogleCredentialsConfig
from google.adk.tools.agent_simulator.agent_simulator_config import AgentSimulatorConfig as _ADK_AgentSimulatorConfig
from google.adk.tools.agent_simulator.agent_simulator_config import InjectionConfig as _ADK_InjectionConfig
from google.adk.tools.agent_simulator.agent_simulator_config import ToolSimulationConfig as _ADK_ToolSimulationConfig
from google.adk.tools.agent_tool import AgentToolConfig as _ADK_AgentToolConfig
from google.adk.tools.bigquery.bigquery_credentials import BigQueryCredentialsConfig as _ADK_BigQueryCredentialsConfig
from google.adk.tools.bigquery.config import BigQueryToolConfig as _ADK_BigQueryToolConfig
from google.adk.tools.bigtable.bigtable_credentials import BigtableCredentialsConfig as _ADK_BigtableCredentialsConfig
from google.adk.tools.data_agent.config import DataAgentToolConfig as _ADK_DataAgentToolConfig
from google.adk.tools.data_agent.credentials import DataAgentCredentialsConfig as _ADK_DataAgentCredentialsConfig
from google.adk.tools.example_tool import ExampleToolConfig as _ADK_ExampleToolConfig
from google.adk.tools.mcp_tool.mcp_toolset import McpToolsetConfig as _ADK_McpToolsetConfig
from google.adk.tools.pubsub.config import PubSubToolConfig as _ADK_PubSubToolConfig
from google.adk.tools.pubsub.pubsub_credentials import PubSubCredentialsConfig as _ADK_PubSubCredentialsConfig
from google.adk.tools.spanner.spanner_credentials import SpannerCredentialsConfig as _ADK_SpannerCredentialsConfig
from google.adk.tools.tool_configs import BaseToolConfig as _ADK_BaseToolConfig
from google.adk.tools.tool_configs import ToolArgsConfig as _ADK_ToolArgsConfig
from google.adk.tools.tool_configs import ToolConfig as _ADK_ToolConfig

from adk_fluent._base import BuilderBase

class AgentConfig(BuilderBase):
    """The config for the YAML schema to create an agent."""
    def __init__(self, root: str) -> None: ...
    def build(self) -> AgentConfig:
        """Resolve into a native ADK AgentConfig."""
        ...

class BaseAgentConfig(BuilderBase):
    """The config for the YAML schema of a BaseAgent."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Optional. The description of the agent."""
        ...
    def agent_class(self, value: Union[Literal[BaseAgent], str]) -> Self:
        """Required. The class of the agent. The value is used to differentiate among different agent classes."""
        ...
    def sub_agents(self, value: Union[list[AgentRefConfig], NoneType]) -> Self:
        """Optional. The sub-agents of the agent."""
        ...
    def before_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The before_agent_callbacks of the agent.

Example:

  ```
  before_agent_callbacks:
    - name: my_library.security_callbacks.before_agent_callback
  ```"""
        ...
    def after_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The after_agent_callbacks of the agent."""
        ...
    def build(self) -> BaseAgentConfig:
        """Resolve into a native ADK BaseAgentConfig."""
        ...

class AgentRefConfig(BuilderBase):
    """The config for the reference to another agent."""
    def __init__(self, ) -> None: ...
    def config_path(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def code(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def build(self) -> AgentRefConfig:
        """Resolve into a native ADK AgentRefConfig."""
        ...

class ArgumentConfig(BuilderBase):
    """An argument passed to a function or a class's constructor."""
    def __init__(self, value: str) -> None: ...
    def name(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def build(self) -> ArgumentConfig:
        """Resolve into a native ADK ArgumentConfig."""
        ...

class CodeConfig(BuilderBase):
    """Code reference config for a variable, a function, or a class."""
    def __init__(self, name: str) -> None: ...
    def args(self, value: Union[list[ArgumentConfig], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> CodeConfig:
        """Resolve into a native ADK CodeConfig."""
        ...

class ContextCacheConfig(BuilderBase):
    """Configuration for context caching across all agents in an app."""
    def __init__(self, ) -> None: ...
    def cache_intervals(self, value: int) -> Self:
        """Maximum number of invocations to reuse the same cache before refreshing it"""
        ...
    def ttl_seconds(self, value: int) -> Self:
        """Time-to-live for cache in seconds"""
        ...
    def min_tokens(self, value: int) -> Self:
        """Minimum estimated request tokens required to enable caching. This compares against the estimated total tokens of the request (system instruction + tools + contents). Context cache storage may have cost. Set higher to avoid caching small requests where overhead may exceed benefits."""
        ...
    def build(self) -> ContextCacheConfig:
        """Resolve into a native ADK ContextCacheConfig."""
        ...

class LlmAgentConfig(BuilderBase):
    """The config for the YAML schema of a LlmAgent."""
    def __init__(self, name: str, instruction: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Optional. The description of the agent."""
        ...
    def history(self, value: Literal[default, none]) -> Self:
        """Optional. LlmAgent.include_contents."""
        ...
    def include_history(self, value: Literal[default, none]) -> Self:
        """Optional. LlmAgent.include_contents."""
        ...
    def instruct(self, value: str) -> Self:
        """Required. LlmAgent.instruction. Dynamic instructions with placeholder support. Behavior: if static_instruction is None, goes to system_instruction; if static_instruction is set, goes to user content after static content."""
        ...
    def outputs(self, value: Union[str, NoneType]) -> Self:
        """Session state key where the agent's response text is stored. Downstream agents and state transforms can read this key."""
        ...
    def static(self, value: Union[Content, str, Image, File, Part, list[Union[str, Image, File, Part]], NoneType]) -> Self:
        """Optional. LlmAgent.static_instruction. Static content sent literally at position 0 without placeholder processing. When set, changes instruction behavior to go to user content instead of system_instruction. Supports context caching. Accepts types.ContentUnion (str, types.Content, types.Part, PIL.Image.Image, types.File, or list[PartUnion])."""
        ...
    def agent_class(self, value: str) -> Self:
        """The value is used to uniquely identify the LlmAgent class. If it is empty, it is by default an LlmAgent."""
        ...
    def sub_agents(self, value: Union[list[AgentRefConfig], NoneType]) -> Self:
        """Optional. The sub-agents of the agent."""
        ...
    def before_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The before_agent_callbacks of the agent.

Example:

  ```
  before_agent_callbacks:
    - name: my_library.security_callbacks.before_agent_callback
  ```"""
        ...
    def after_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The after_agent_callbacks of the agent."""
        ...
    def model(self, value: Union[str, NoneType]) -> Self:
        """Optional. LlmAgent.model. Provide a model name string (e.g. "gemini-2.0-flash"). If not set, the model will be inherited from the ancestor or fall back to the system default (gemini-2.5-flash unless overridden via LlmAgent.set_default_model). To construct a model instance from code, use model_code."""
        ...
    def model_code(self, value: Union[CodeConfig, NoneType]) -> Self:
        """Optional. A CodeConfig that instantiates a BaseLlm implementation such as LiteLlm with custom arguments (API base, fallbacks, etc.). Cannot be set together with `model`."""
        ...
    def disallow_transfer_to_parent(self, value: Union[bool, NoneType]) -> Self:
        """Prevent this agent from transferring control back to its parent. Also forces a handoff back to parent on the next turn, preventing the user from getting stuck. See also ``.isolate()``."""
        ...
    def disallow_transfer_to_peers(self, value: Union[bool, NoneType]) -> Self:
        """Prevent this agent from transferring control to sibling agents. See also ``.isolate()``."""
        ...
    def input_schema(self, value: Union[CodeConfig, NoneType]) -> Self:
        """Schema defining the expected input structure when this agent is invoked as a tool by another agent."""
        ...
    def output_schema(self, value: Union[CodeConfig, NoneType]) -> Self:
        """Pydantic model enforcing structured JSON output. When set, the agent replies only with data matching this schema and cannot use tools. Use the ``@`` operator as shorthand: ``agent @ MyModel``."""
        ...
    def tools(self, value: Union[list[ToolConfig], NoneType]) -> Self:
        """Optional. LlmAgent.tools.

Examples:

  For ADK built-in tools in `google.adk.tools` package, they can be referenced
  directly with the name:

    ```
    tools:
      - name: google_search
      - name: load_memory
    ```

  For user-defined tools, they can be referenced with fully qualified name:

    ```
    tools:
      - name: my_library.my_tools.my_tool
    ```

  For tools that needs to be created via functions:

    ```
    tools:
      - name: my_library.my_tools.create_tool
        args:
          - name: param1
            value: value1
          - name: param2
            value: value2
    ```

  For more advanced tools, instead of specifying arguments in config, it's
  recommended to define them in Python files and reference them. E.g.,

    ```
    # tools.py
    my_mcp_toolset = McpToolset(
        connection_params=StdioServerParameters(
            command="npx",
            args=["-y", "@notionhq/notion-mcp-server"],
            env={"OPENAPI_MCP_HEADERS": NOTION_HEADERS},
        )
    )
    ```

  Then, reference the toolset in config:

  ```
  tools:
    - name: tools.my_mcp_toolset
  ```"""
        ...
    def before_model_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. LlmAgent.before_model_callbacks.

Example:

  ```
  before_model_callbacks:
    - name: my_library.callbacks.before_model_callback
  ```"""
        ...
    def after_model_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. LlmAgent.after_model_callbacks."""
        ...
    def before_tool_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. LlmAgent.before_tool_callbacks."""
        ...
    def after_tool_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. LlmAgent.after_tool_callbacks."""
        ...
    def generate_content_config(self, value: Union[GenerateContentConfig, NoneType]) -> Self:
        """Optional. LlmAgent.generate_content_config."""
        ...
    def build(self) -> LlmAgentConfig:
        """Resolve into a native ADK LlmAgentConfig."""
        ...

class LoopAgentConfig(BuilderBase):
    """The config for the YAML schema of a LoopAgent."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Optional. The description of the agent."""
        ...
    def agent_class(self, value: str) -> Self:
        """The value is used to uniquely identify the LoopAgent class."""
        ...
    def sub_agents(self, value: Union[list[AgentRefConfig], NoneType]) -> Self:
        """Optional. The sub-agents of the agent."""
        ...
    def before_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The before_agent_callbacks of the agent.

Example:

  ```
  before_agent_callbacks:
    - name: my_library.security_callbacks.before_agent_callback
  ```"""
        ...
    def after_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The after_agent_callbacks of the agent."""
        ...
    def max_iterations(self, value: Union[int, NoneType]) -> Self:
        """Optional. LoopAgent.max_iterations."""
        ...
    def build(self) -> LoopAgentConfig:
        """Resolve into a native ADK LoopAgentConfig."""
        ...

class ParallelAgentConfig(BuilderBase):
    """The config for the YAML schema of a ParallelAgent."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Optional. The description of the agent."""
        ...
    def agent_class(self, value: str) -> Self:
        """The value is used to uniquely identify the ParallelAgent class."""
        ...
    def sub_agents(self, value: Union[list[AgentRefConfig], NoneType]) -> Self:
        """Optional. The sub-agents of the agent."""
        ...
    def before_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The before_agent_callbacks of the agent.

Example:

  ```
  before_agent_callbacks:
    - name: my_library.security_callbacks.before_agent_callback
  ```"""
        ...
    def after_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The after_agent_callbacks of the agent."""
        ...
    def build(self) -> ParallelAgentConfig:
        """Resolve into a native ADK ParallelAgentConfig."""
        ...

class RunConfig(BuilderBase):
    """Configs for runtime behavior of agents."""
    def __init__(self, ) -> None: ...
    def speech_config(self, value: Union[SpeechConfig, NoneType]) -> Self:
        """"""
        ...
    def response_modalities(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def save_input_blobs_as_artifacts(self, value: bool) -> Self:
        """Whether or not to save the input blobs as artifacts. DEPRECATED: Use SaveFilesAsArtifactsPlugin instead for better control and flexibility. See google.adk.plugins.SaveFilesAsArtifactsPlugin."""
        ...
    def support_cfc(self, value: bool) -> Self:
        """"""
        ...
    def streaming_mode(self, value: StreamingMode) -> Self:
        """"""
        ...
    def output_audio_transcription(self, value: Union[AudioTranscriptionConfig, NoneType]) -> Self:
        """"""
        ...
    def input_audio_transcription(self, value: Union[AudioTranscriptionConfig, NoneType]) -> Self:
        """"""
        ...
    def realtime_input_config(self, value: Union[RealtimeInputConfig, NoneType]) -> Self:
        """"""
        ...
    def enable_affective_dialog(self, value: Union[bool, NoneType]) -> Self:
        """"""
        ...
    def proactivity(self, value: Union[ProactivityConfig, NoneType]) -> Self:
        """"""
        ...
    def session_resumption(self, value: Union[SessionResumptionConfig, NoneType]) -> Self:
        """"""
        ...
    def context_window_compression(self, value: Union[ContextWindowCompressionConfig, NoneType]) -> Self:
        """"""
        ...
    def save_live_blob(self, value: bool) -> Self:
        """"""
        ...
    def tool_thread_pool_config(self, value: Union[ToolThreadPoolConfig, NoneType]) -> Self:
        """"""
        ...
    def save_live_audio(self, value: bool) -> Self:
        """DEPRECATED: Use save_live_blob instead. If set to True, it saves live video and audio data to session and artifact service."""
        ...
    def max_llm_calls(self, value: int) -> Self:
        """"""
        ...
    def custom_metadata(self, value: Union[dict[str, Any], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> RunConfig:
        """Resolve into a native ADK RunConfig."""
        ...

class ToolThreadPoolConfig(BuilderBase):
    """Configuration for the tool thread pool executor."""
    def __init__(self, ) -> None: ...
    def max_workers(self, value: int) -> Self:
        """Maximum number of worker threads in the pool."""
        ...
    def build(self) -> ToolThreadPoolConfig:
        """Resolve into a native ADK ToolThreadPoolConfig."""
        ...

class SequentialAgentConfig(BuilderBase):
    """The config for the YAML schema of a SequentialAgent."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Optional. The description of the agent."""
        ...
    def agent_class(self, value: str) -> Self:
        """The value is used to uniquely identify the SequentialAgent class."""
        ...
    def sub_agents(self, value: Union[list[AgentRefConfig], NoneType]) -> Self:
        """Optional. The sub-agents of the agent."""
        ...
    def before_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The before_agent_callbacks of the agent.

Example:

  ```
  before_agent_callbacks:
    - name: my_library.security_callbacks.before_agent_callback
  ```"""
        ...
    def after_agent_callbacks(self, value: Union[list[CodeConfig], NoneType]) -> Self:
        """Optional. The after_agent_callbacks of the agent."""
        ...
    def build(self) -> SequentialAgentConfig:
        """Resolve into a native ADK SequentialAgentConfig."""
        ...

class EventsCompactionConfig(BuilderBase):
    """The config of event compaction for an application."""
    def __init__(self, compaction_interval: str, overlap_size: str) -> None: ...
    def summarizer(self, value: Union[BaseEventsSummarizer, NoneType]) -> Self:
        """"""
        ...
    def token_threshold(self, value: Union[int, NoneType]) -> Self:
        """"""
        ...
    def event_retention_size(self, value: Union[int, NoneType]) -> Self:
        """"""
        ...
    def build(self) -> EventsCompactionConfig:
        """Resolve into a native ADK EventsCompactionConfig."""
        ...

class ResumabilityConfig(BuilderBase):
    """The config of the resumability for an application."""
    def __init__(self, ) -> None: ...
    def is_resumable(self, value: bool) -> Self:
        """"""
        ...
    def build(self) -> ResumabilityConfig:
        """Resolve into a native ADK ResumabilityConfig."""
        ...

class FeatureConfig(BuilderBase):
    """Feature configuration."""
    def __init__(self, stage: str) -> None: ...
    def default_on(self, value: bool) -> Self:
        """Set the ``default_on`` parameter."""
        ...
    def build(self) -> FeatureConfig:
        """Resolve into a native ADK FeatureConfig."""
        ...

class AudioCacheConfig(BuilderBase):
    """Configuration for audio caching behavior."""
    def __init__(self, ) -> None: ...
    def max_cache_size_bytes(self, value: int) -> Self:
        """Set the ``max_cache_size_bytes`` parameter."""
        ...
    def max_cache_duration_seconds(self, value: float) -> Self:
        """Set the ``max_cache_duration_seconds`` parameter."""
        ...
    def auto_flush_threshold(self, value: int) -> Self:
        """Set the ``auto_flush_threshold`` parameter."""
        ...
    def build(self) -> AudioCacheConfig:
        """Resolve into a native ADK AudioCacheConfig."""
        ...

class SimplePromptOptimizerConfig(BuilderBase):
    """Configuration for the IterativePromptOptimizer."""
    def __init__(self, ) -> None: ...
    def optimizer_model(self, value: str) -> Self:
        """The model used to analyze the eval results and optimize the agent."""
        ...
    def model_configuration(self, value: GenerateContentConfig) -> Self:
        """The configuration for the optimizer model."""
        ...
    def num_iterations(self, value: int) -> Self:
        """The number of optimization rounds to run."""
        ...
    def batch_size(self, value: int) -> Self:
        """The number of training examples to use for scoring each candidate."""
        ...
    def build(self) -> SimplePromptOptimizerConfig:
        """Resolve into a native ADK SimplePromptOptimizerConfig."""
        ...

class BigQueryLoggerConfig(BuilderBase):
    """Configuration for the BigQueryAgentAnalyticsPlugin."""
    def __init__(self, ) -> None: ...
    def enabled(self, value: bool) -> Self:
        """Set the ``enabled`` parameter."""
        ...
    def event_allowlist(self, value: list[str] | None) -> Self:
        """Set the ``event_allowlist`` parameter."""
        ...
    def event_denylist(self, value: list[str] | None) -> Self:
        """Set the ``event_denylist`` parameter."""
        ...
    def max_content_length(self, value: int) -> Self:
        """Set the ``max_content_length`` parameter."""
        ...
    def table_id(self, value: str) -> Self:
        """Set the ``table_id`` parameter."""
        ...
    def clustering_fields(self, value: list[str]) -> Self:
        """Set the ``clustering_fields`` parameter."""
        ...
    def log_multi_modal_content(self, value: bool) -> Self:
        """Set the ``log_multi_modal_content`` parameter."""
        ...
    def retry_config(self, value: RetryConfig) -> Self:
        """Set the ``retry_config`` parameter."""
        ...
    def batch_size(self, value: int) -> Self:
        """Set the ``batch_size`` parameter."""
        ...
    def batch_flush_interval(self, value: float) -> Self:
        """Set the ``batch_flush_interval`` parameter."""
        ...
    def shutdown_timeout(self, value: float) -> Self:
        """Set the ``shutdown_timeout`` parameter."""
        ...
    def queue_max_size(self, value: int) -> Self:
        """Set the ``queue_max_size`` parameter."""
        ...
    def content_formatter(self, value: Optional[Callable[[Any, str], Any]]) -> Self:
        """Set the ``content_formatter`` parameter."""
        ...
    def gcs_bucket_name(self, value: Optional[str]) -> Self:
        """Set the ``gcs_bucket_name`` parameter."""
        ...
    def connection_id(self, value: Optional[str]) -> Self:
        """Set the ``connection_id`` parameter."""
        ...
    def log_session_metadata(self, value: bool) -> Self:
        """Set the ``log_session_metadata`` parameter."""
        ...
    def custom_tags(self, value: dict[str, Any]) -> Self:
        """Set the ``custom_tags`` parameter."""
        ...
    def build(self) -> BigQueryLoggerConfig:
        """Resolve into a native ADK BigQueryLoggerConfig."""
        ...

class RetryConfig(BuilderBase):
    """Configuration for retrying failed BigQuery write operations."""
    def __init__(self, ) -> None: ...
    def max_retries(self, value: int) -> Self:
        """Set the ``max_retries`` parameter."""
        ...
    def initial_delay(self, value: float) -> Self:
        """Set the ``initial_delay`` parameter."""
        ...
    def multiplier(self, value: float) -> Self:
        """Set the ``multiplier`` parameter."""
        ...
    def max_delay(self, value: float) -> Self:
        """Set the ``max_delay`` parameter."""
        ...
    def build(self) -> RetryConfig:
        """Resolve into a native ADK RetryConfig."""
        ...

class GetSessionConfig(BuilderBase):
    """The configuration of getting a session."""
    def __init__(self, ) -> None: ...
    def num_recent_events(self, value: Union[int, NoneType]) -> Self:
        """"""
        ...
    def after_timestamp(self, value: Union[float, NoneType]) -> Self:
        """"""
        ...
    def build(self) -> GetSessionConfig:
        """Resolve into a native ADK GetSessionConfig."""
        ...

class BaseGoogleCredentialsConfig(BuilderBase):
    """Base Google Credentials Configuration for Google API tools (Experimental)."""
    def __init__(self, ) -> None: ...
    def credentials(self, value: Union[Credentials, NoneType]) -> Self:
        """"""
        ...
    def external_access_token_key(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_secret(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def scopes(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> BaseGoogleCredentialsConfig:
        """Resolve into a native ADK BaseGoogleCredentialsConfig."""
        ...

class AgentSimulatorConfig(BuilderBase):
    """Configuration for AgentSimulator."""
    def __init__(self, ) -> None: ...
    def tool_simulation_configs(self, value: list[ToolSimulationConfig]) -> Self:
        """"""
        ...
    def simulation_model(self, value: str) -> Self:
        """"""
        ...
    def simulation_model_configuration(self, value: GenerateContentConfig) -> Self:
        """"""
        ...
    def tracing_path(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def environment_data(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def build(self) -> AgentSimulatorConfig:
        """Resolve into a native ADK AgentSimulatorConfig."""
        ...

class InjectionConfig(BuilderBase):
    """Injection configuration for a tool."""
    def __init__(self, ) -> None: ...
    def injection_probability(self, value: float) -> Self:
        """"""
        ...
    def match_args(self, value: Union[dict[str, Any], NoneType]) -> Self:
        """"""
        ...
    def injected_latency_seconds(self, value: float) -> Self:
        """"""
        ...
    def random_seed(self, value: Union[int, NoneType]) -> Self:
        """"""
        ...
    def injected_error(self, value: Union[InjectedError, NoneType]) -> Self:
        """"""
        ...
    def injected_response(self, value: Union[dict[str, Any], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> InjectionConfig:
        """Resolve into a native ADK InjectionConfig."""
        ...

class ToolSimulationConfig(BuilderBase):
    """Simulation configuration for a single tool."""
    def __init__(self, tool_name: str) -> None: ...
    def injection_configs(self, value: list[InjectionConfig]) -> Self:
        """"""
        ...
    def mock_strategy_type(self, value: MockStrategy) -> Self:
        """"""
        ...
    def build(self) -> ToolSimulationConfig:
        """Resolve into a native ADK ToolSimulationConfig."""
        ...

class AgentToolConfig(BuilderBase):
    """The config for the AgentTool."""
    def __init__(self, agent: str) -> None: ...
    def skip_summarization(self, value: bool) -> Self:
        """"""
        ...
    def include_plugins(self, value: bool) -> Self:
        """"""
        ...
    def build(self) -> AgentToolConfig:
        """Resolve into a native ADK AgentToolConfig."""
        ...

class BigQueryCredentialsConfig(BuilderBase):
    """BigQuery Credentials Configuration for Google API tools (Experimental)."""
    def __init__(self, ) -> None: ...
    def credentials(self, value: Union[Credentials, NoneType]) -> Self:
        """"""
        ...
    def external_access_token_key(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_secret(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def scopes(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> BigQueryCredentialsConfig:
        """Resolve into a native ADK BigQueryCredentialsConfig."""
        ...

class BigQueryToolConfig(BuilderBase):
    """Configuration for BigQuery tools."""
    def __init__(self, ) -> None: ...
    def write_mode(self, value: WriteMode) -> Self:
        """"""
        ...
    def maximum_bytes_billed(self, value: Union[int, NoneType]) -> Self:
        """"""
        ...
    def max_query_result_rows(self, value: int) -> Self:
        """"""
        ...
    def application_name(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def compute_project_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def location(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def job_labels(self, value: Union[dict[str, str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> BigQueryToolConfig:
        """Resolve into a native ADK BigQueryToolConfig."""
        ...

class BigtableCredentialsConfig(BuilderBase):
    """Bigtable Credentials Configuration for Google API tools (Experimental)."""
    def __init__(self, ) -> None: ...
    def credentials(self, value: Union[Credentials, NoneType]) -> Self:
        """"""
        ...
    def external_access_token_key(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_secret(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def scopes(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> BigtableCredentialsConfig:
        """Resolve into a native ADK BigtableCredentialsConfig."""
        ...

class DataAgentToolConfig(BuilderBase):
    """Configuration for Data Agent tools."""
    def __init__(self, ) -> None: ...
    def max_query_result_rows(self, value: int) -> Self:
        """"""
        ...
    def build(self) -> DataAgentToolConfig:
        """Resolve into a native ADK DataAgentToolConfig."""
        ...

class DataAgentCredentialsConfig(BuilderBase):
    """Data Agent Credentials Configuration for Google API tools."""
    def __init__(self, ) -> None: ...
    def credentials(self, value: Union[Credentials, NoneType]) -> Self:
        """"""
        ...
    def external_access_token_key(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_secret(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def scopes(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> DataAgentCredentialsConfig:
        """Resolve into a native ADK DataAgentCredentialsConfig."""
        ...

class ExampleToolConfig(BuilderBase):
    """Fluent builder for ExampleToolConfig."""
    def __init__(self, examples: str) -> None: ...
    def build(self) -> ExampleToolConfig:
        """Resolve into a native ADK ExampleToolConfig."""
        ...

class McpToolsetConfig(BuilderBase):
    """The config for McpToolset."""
    def __init__(self, ) -> None: ...
    def stdio_server_params(self, value: Union[StdioServerParameters, NoneType]) -> Self:
        """"""
        ...
    def stdio_connection_params(self, value: Union[StdioConnectionParams, NoneType]) -> Self:
        """"""
        ...
    def sse_connection_params(self, value: Union[SseConnectionParams, NoneType]) -> Self:
        """"""
        ...
    def streamable_http_connection_params(self, value: Union[StreamableHTTPConnectionParams, NoneType]) -> Self:
        """"""
        ...
    def tool_filter(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def tool_name_prefix(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def auth_scheme(self, value: Union[APIKey, HTTPBase, OAuth2, OpenIdConnect, HTTPBearer, OpenIdConnectWithConfig, NoneType]) -> Self:
        """"""
        ...
    def auth_credential(self, value: Union[AuthCredential, NoneType]) -> Self:
        """"""
        ...
    def use_mcp_resources(self, value: bool) -> Self:
        """"""
        ...
    def build(self) -> McpToolsetConfig:
        """Resolve into a native ADK McpToolsetConfig."""
        ...

class PubSubToolConfig(BuilderBase):
    """Configuration for Pub/Sub tools."""
    def __init__(self, ) -> None: ...
    def project_id(self, value: str | None) -> Self:
        """"""
        ...
    def build(self) -> PubSubToolConfig:
        """Resolve into a native ADK PubSubToolConfig."""
        ...

class PubSubCredentialsConfig(BuilderBase):
    """Pub/Sub Credentials Configuration for Google API tools (Experimental)."""
    def __init__(self, ) -> None: ...
    def credentials(self, value: Union[Credentials, NoneType]) -> Self:
        """"""
        ...
    def external_access_token_key(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_secret(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def scopes(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> PubSubCredentialsConfig:
        """Resolve into a native ADK PubSubCredentialsConfig."""
        ...

class SpannerCredentialsConfig(BuilderBase):
    """Spanner Credentials Configuration for Google API tools (Experimental)."""
    def __init__(self, ) -> None: ...
    def credentials(self, value: Union[Credentials, NoneType]) -> Self:
        """"""
        ...
    def external_access_token_key(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_id(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def client_secret(self, value: Union[str, NoneType]) -> Self:
        """"""
        ...
    def scopes(self, value: Union[list[str], NoneType]) -> Self:
        """"""
        ...
    def build(self) -> SpannerCredentialsConfig:
        """Resolve into a native ADK SpannerCredentialsConfig."""
        ...

class BaseToolConfig(BuilderBase):
    """The base class for all tool configs."""
    def __init__(self, ) -> None: ...
    def build(self) -> BaseToolConfig:
        """Resolve into a native ADK BaseToolConfig."""
        ...

class ToolArgsConfig(BuilderBase):
    """Config to host free key-value pairs for the args in ToolConfig."""
    def __init__(self, ) -> None: ...
    def build(self) -> ToolArgsConfig:
        """Resolve into a native ADK ToolArgsConfig."""
        ...

class ToolConfig(BuilderBase):
    """The configuration for a tool."""
    def __init__(self, name: str) -> None: ...
    def args(self, value: Union[ToolArgsConfig, NoneType]) -> Self:
        """The args for the tool."""
        ...
    def build(self) -> ToolConfig:
        """Resolve into a native ADK ToolConfig."""
        ...
