# AUTO-GENERATED by adk-fluent generator — do not edit manually
# Generated from google-adk 1.25.0
# Timestamp: 2026-02-18T23:50:40.389505+00:00

from collections.abc import AsyncGenerator, Callable
from typing import Any, Self

from google.adk.agents.loop_agent import LoopAgent
from google.adk.agents.parallel_agent import ParallelAgent
from google.adk.agents.sequential_agent import SequentialAgent

from adk_fluent._base import BuilderBase

class Loop(BuilderBase):
    """A shell agent that run its sub-agents in a loop."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Set the ``description`` field."""
        ...
    def after_agent(self, fn: Callable) -> Self:
        """Append callback to ``after_agent_callback``. Multiple calls accumulate."""
        ...
    def before_agent(self, fn: Callable) -> Self:
        """Append callback to ``before_agent_callback``. Multiple calls accumulate."""
        ...
    def after_agent_if(self, condition: bool, fn: Callable) -> Self:
        """Append callback to ``after_agent_callback`` only if *condition* is True."""
        ...
    def before_agent_if(self, condition: bool, fn: Callable) -> Self:
        """Append callback to ``before_agent_callback`` only if *condition* is True."""
        ...
    def sub_agents(self, value: list[BaseAgent]) -> Self:
        """"""
        ...
    def max_iterations(self, value: Union[int, NoneType]) -> Self:
        """"""
        ...
    def step(self, agent: BaseAgent | AgentBuilder) -> Self:
        """Append an agent as the next step (lazy — built at .build() time)."""
        ...
    def to_ir(self):
        """Convert this Loop builder to a LoopNode IR node."""
        ...
    def build(self) -> LoopAgent:
        """Resolve into a native ADK LoopAgent."""
        ...

class FanOut(BuilderBase):
    """A shell agent that runs its sub-agents in parallel in an isolated manner."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Set the ``description`` field."""
        ...
    def after_agent(self, fn: Callable) -> Self:
        """Append callback to ``after_agent_callback``. Multiple calls accumulate."""
        ...
    def before_agent(self, fn: Callable) -> Self:
        """Append callback to ``before_agent_callback``. Multiple calls accumulate."""
        ...
    def after_agent_if(self, condition: bool, fn: Callable) -> Self:
        """Append callback to ``after_agent_callback`` only if *condition* is True."""
        ...
    def before_agent_if(self, condition: bool, fn: Callable) -> Self:
        """Append callback to ``before_agent_callback`` only if *condition* is True."""
        ...
    def sub_agents(self, value: list[BaseAgent]) -> Self:
        """"""
        ...
    def branch(self, agent: BaseAgent | AgentBuilder) -> Self:
        """Add a parallel branch agent (lazy — built at .build() time)."""
        ...
    def step(self, agent: BaseAgent | AgentBuilder) -> Self:
        """Alias for .branch() — add a parallel branch. Consistent with Pipeline/Loop API."""
        ...
    def to_ir(self):
        """Convert this FanOut builder to a ParallelNode IR node."""
        ...
    def build(self) -> ParallelAgent:
        """Resolve into a native ADK ParallelAgent."""
        ...

class Pipeline(BuilderBase):
    """A shell agent that runs its sub-agents in sequence."""
    def __init__(self, name: str) -> None: ...
    def describe(self, value: str) -> Self:
        """Set the ``description`` field."""
        ...
    def after_agent(self, fn: Callable) -> Self:
        """Append callback to ``after_agent_callback``. Multiple calls accumulate."""
        ...
    def before_agent(self, fn: Callable) -> Self:
        """Append callback to ``before_agent_callback``. Multiple calls accumulate."""
        ...
    def after_agent_if(self, condition: bool, fn: Callable) -> Self:
        """Append callback to ``after_agent_callback`` only if *condition* is True."""
        ...
    def before_agent_if(self, condition: bool, fn: Callable) -> Self:
        """Append callback to ``before_agent_callback`` only if *condition* is True."""
        ...
    def sub_agents(self, value: list[BaseAgent]) -> Self:
        """"""
        ...
    def step(self, agent: BaseAgent | AgentBuilder) -> Self:
        """Append an agent as the next step (lazy — built at .build() time)."""
        ...
    def to_ir(self):
        """Convert this Pipeline builder to a SequenceNode IR node."""
        ...
    def build(self) -> SequentialAgent:
        """Resolve into a native ADK SequentialAgent."""
        ...
