"""Type stubs for _ui_generated.py — IDE completion support."""

from typing import Any

from adk_fluent._ui import UIAction, UIBinding, UICheck, UIComponent


class _GeneratedFactories:
    @staticmethod
    def text(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def image(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def icon(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def video(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def audio(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def row(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def column(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def list_(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def card(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def tabs(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def modal(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def divider(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def button(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def text_field(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def checkbox(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def choice(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def slider(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def date_time(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def required(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def regex(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def length(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def numeric(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def email(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def formatString(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def formatNumber(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def formatCurrency(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def formatDate(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def pluralize(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def openUrl(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def and_(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def or_(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def not_(*args: Any, **kwargs: Any) -> UICheck: ...
    @staticmethod
    def heading(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def h1(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def h2(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def h3(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def h4(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def h5(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def caption(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def paragraph(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def primary_button(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def link_button(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def long_text(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def password(*args: Any, **kwargs: Any) -> UIComponent: ...
    @staticmethod
    def number_input(*args: Any, **kwargs: Any) -> UIComponent: ...
