name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the current pain point?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would the API look like? Show example code if possible.
      render: python
      placeholder: |
        # What the new API could look like:
        agent = Agent("test").new_method(...)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've tried.
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - New builder method
        - New operator / primitive
        - Generator pipeline improvement
        - Documentation
        - Developer experience
        - Other
    validations:
      required: true
