// GENERATED BY shared/scripts/flux — DO NOT EDIT
//
// Renderer scaffold for ``FluxStack`` (extends basic-catalog ``Column``).
// Replace this file's body with a pixel-perfect implementation in W5.
// To opt out of re-generation, change the first line of this file to
// ``// flux:scaffold-user`` — the build will preserve everything below it.

import type { FluxElement, FluxNode, FluxRenderContext, FluxRenderer } from "./types.js";

/**
 * Default FluxStack renderer. Emits a minimal container that exposes the
 * node's props via data attributes so the visual runner can detect
 * which component it is looking at even before the real renderer lands.
 */
const FluxStack: FluxRenderer = (node: FluxNode, _ctx: FluxRenderContext): FluxElement => {
  const style: Record<string, string | number> = {
    // CSS custom properties — the theme pack is injected at the surface
    // root by ``<FluxThemeProvider>`` (W5). Authors consume tokens by
    // name, not raw values.
    color: "var(--flux-color-text-primary)",
    backgroundColor: "var(--flux-color-bg-surface)",
    padding: "var(--flux-space-2)",
    borderRadius: "var(--flux-radius-md)",
  };
  return {
    type: "div",
    key: node.id,
    props: {
      "data-flux-component": node.component,
      "data-flux-node-id": node.id,
      style,
      children: ("label" in node && typeof node.label === "string") ? node.label : node.component,
    },
  };
};

export default FluxStack;
