"""Emit ``python/src/adk_fluent/_flux_gen.py`` — Python factories per component.

Each factory is a thin typed wrapper that materialises a flux node dict
from kwargs. The generated module re-uses nothing from the runtime ADK
side so it can be imported in isolation (the ``_ui.py`` integration in
W4 consumes these factories).

Generated file contract:

  * First line is a ``# GENERATED BY …`` marker (preserves idempotence).
  * Ruff-clean on first emit (line length capped, simple imports, PEP 604
    union syntax, sorted imports).
  * One factory per component, named ``flux_<snake>``.
  * Signatures derive from the component block's ``jsonSchema`` — the
    ``properties`` map + ``required`` list together describe the prop
    surface. Defaults from ``jsonSchema.properties[k].default`` become
    Python defaults (literals only).

``jsonSchema`` nodes we lower:

  - ``"type": "string"`` → ``str``
  - ``"type": "string", "enum": [...]`` → ``Literal[...]``
  - ``"type": "string", "const": X`` → ``Literal[X]``
  - ``"type": "number"`` / ``"integer"`` → ``float`` / ``int``
  - ``"type": "boolean"`` → ``bool``
  - ``"type": "object"`` → ``dict[str, Any]`` (details belong to the
    caller; ADK already wires dict-shape validation via the catalog
    schema at render time)
  - ``"type": "array"`` → ``list[Any]``
  - everything else → ``Any``

Properties marked optional in ``required`` are given ``None`` defaults
unless ``default`` is present. Every signature is keyword-only.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any

MARKER = "# GENERATED BY shared/scripts/flux — DO NOT EDIT"


def _camel_to_snake(name: str) -> str:
    """FluxButton → flux_button, FluxTextField → flux_text_field."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _py_literal(value: Any) -> str:
    """Render a JSON-schema default as a Python literal."""
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_py_literal(v) for v in value)
        return f"[{inner}]"
    if isinstance(value, dict):
        # Stable-order dict literal — rare in defaults.
        inner = ", ".join(f"{_py_literal(k)}: {_py_literal(v)}" for k, v in sorted(value.items()))
        return "{" + inner + "}"
    return repr(value)


def _prop_type(prop: dict[str, Any]) -> str:
    """Derive a Python type annotation from a JSON Schema property node."""
    # const first (most specific).
    if "const" in prop:
        val = prop["const"]
        if isinstance(val, str):
            return f"Literal[{val!r}]"
        return "Any"
    if "enum" in prop and isinstance(prop["enum"], list) and prop["enum"]:
        parts = []
        for v in prop["enum"]:
            if isinstance(v, str):
                parts.append(repr(v))
            else:
                # Non-string enums are unusual; fall back.
                return "Any"
        return f"Literal[{', '.join(parts)}]"
    t = prop.get("type")
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "object":
        return "dict[str, Any]"
    if t == "array":
        return "list[Any]"
    return "Any"


# Props that the factory fills itself from the component spec — authors
# never pass these.
_HIDDEN_PROPS = frozenset({"component"})


def _render_factory(spec: dict[str, Any]) -> str:
    """Return the Python source for one factory."""
    name = spec["name"]
    snake = _camel_to_snake(name)
    js = spec.get("jsonSchema") or {}
    props: dict[str, Any] = js.get("properties") or {}
    required: list[str] = list(js.get("required") or [])

    # Required params (no default) come first; the rest are optional with
    # a typed default (None unless the schema declares one).
    req_params: list[tuple[str, str]] = []
    opt_params: list[tuple[str, str]] = []

    # Sort: required in the order listed by the schema, optional
    # alphabetically. Alphabetic order for optionals keeps two runs with
    # cosmetic-only spec edits producing the same signature.
    required_seen: set[str] = set()
    for key in required:
        if key in _HIDDEN_PROPS:
            continue
        if key not in props:
            continue
        ann = _prop_type(props[key])
        req_params.append((key, ann))
        required_seen.add(key)

    optional_keys = sorted(k for k in props if k not in required_seen and k not in _HIDDEN_PROPS)
    for key in optional_keys:
        prop = props[key]
        ann = _prop_type(prop)
        if "default" in prop:
            default_repr = _py_literal(prop["default"])
        else:
            ann = f"{ann} | None"
            default_repr = "None"
        opt_params.append((key, f"{ann} = {default_repr}"))

    lines: list[str] = []
    description = (spec.get("llm") or {}).get("description") or f"{name} component factory."
    summary = description.strip().splitlines()[0][:120]
    lines.append(f"def {snake}(")
    lines.append("    *,")
    for key, ann in req_params:
        lines.append(f"    {key}: {ann},")
    for key, decl in opt_params:
        lines.append(f"    {key}: {decl},")
    lines.append(") -> dict[str, Any]:")
    lines.append(f'    """{summary}')
    lines.append("")
    lines.append(f"    Emits a ``{name}`` node. See")
    lines.append(f"    ``catalog/flux/catalog.json#/components/{name}``")
    lines.append("    for the full schema and renderer contract.")
    lines.append('    """')
    lines.append("    node: dict[str, Any] = {")
    lines.append(f'        "component": "{name}",')
    # Required kwargs become dict entries unconditionally.
    for key, _ann in req_params:
        lines.append(f'        "{key}": {key},')
    lines.append("    }")
    # Optionals only land in the dict when non-None (defaults from the
    # schema are passed through verbatim; the renderer interprets them).
    for key, _decl in opt_params:
        lines.append(f"    if {key} is not None:")
        lines.append(f'        node["{key}"] = {key}')
    lines.append("    return node")
    lines.append("")
    return "\n".join(lines)


def _module_header(catalog_rel: str) -> str:
    return (
        f'"""{MARKER}\n'
        "\n"
        "Typed Python factories for every flux component. Every function\n"
        f"emits a plain dict that validates against the component block in\n"
        f"``{catalog_rel}``. Import via ``from adk_fluent._flux_gen import ...``;\n"
        "the public ``UI.*`` surface in ``_ui.py`` layers ergonomic wrappers\n"
        "on top once W4 lands.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "from pathlib import Path\n"
        "from typing import Any, Literal\n"
        "\n"
        "# Absolute path to the catalog JSON this module was generated from.\n"
        "# Consumers that want to re-validate a built node at runtime can\n"
        "# load FLUX_CATALOG_PATH and index into ``components[<Name>]``.\n"
        "FLUX_CATALOG_PATH: Path = (\n"
        f"    Path(__file__).resolve().parents[3] / {json.dumps(catalog_rel)}\n"
        ")\n"
        "\n"
    )


def _ruff_fixup(path: Path) -> None:
    """Best-effort ruff format on the emitted file.

    Ruff is a project dev-dep — if it isn't importable we silently skip.
    The generated source is written to be ruff-clean without this pass so
    CI stays green even without ruff installed.
    """
    try:
        subprocess.run(
            ["ruff", "format", str(path)],
            check=False,
            capture_output=True,
        )
    except FileNotFoundError:
        return


def emit(
    catalog: dict[str, Any],
    *,
    root: Path,
) -> Path:
    out_path = root / "python" / "src" / "adk_fluent" / "_flux_gen.py"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # python/src/adk_fluent/_flux_gen.py → parents[3] == root
    catalog_rel = "catalog/flux/catalog.json"
    parts: list[str] = [_module_header(catalog_rel)]
    for name in sorted(catalog.get("components") or {}):
        spec = catalog["components"][name]
        parts.append(_render_factory(spec))
    source = "".join(parts).rstrip() + "\n"
    out_path.write_text(source, encoding="utf-8")
    _ruff_fixup(out_path)
    return out_path
