"""Emit React renderer scaffolds — one file per component.

Outputs (under ``ts/src/flux/renderer/``):

  * ``<Name>.tsx``  — a minimal scaffold that wires tokens via CSS custom
                      properties. The W5 workstream replaces these bodies
                      with real renderers. Files whose first line is
                      ``// flux:scaffold-user`` are preserved verbatim to
                      protect hand-written code.
  * ``types.ts``    — the ``FluxNode`` / ``FluxRenderContext`` /
                      ``FluxRenderer`` interfaces from ARCHITECTURE §8.
  * ``index.ts``    — re-export map keyed by component name. Consumed by
                      the visual runner and the ``T.a2ui(catalog="flux")``
                      integration once W5 lands.

Every emitted TSX scaffold is a self-contained React functional component
accepting ``(node, ctx)`` and returning a single element that uses token
CSS variables directly. No imports from other flux renderers — each
component is independently replaceable.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

MARKER = "// GENERATED BY shared/scripts/flux — DO NOT EDIT"
USER_MARKER = "// flux:scaffold-user"


_TYPES_TS = f"""{MARKER}
//
// Public renderer contract. See ARCHITECTURE.md §8.
//
// Hand-written renderers should satisfy ``FluxRenderer`` and be exported
// as the default export of their module. The generator never touches a
// file whose first line starts with ``{USER_MARKER}``.
//
// We intentionally DO NOT import ``ReactElement`` from ``react`` here:
// ``react`` is not a declared dependency of this package. W5 tightens the
// typing (and takes the real React dep) once the visual runner lands.

/**
 * Structural stand-in for a React element. Anything that matches this
 * shape (``type`` + ``props`` + ``$$typeof``) is accepted by React's
 * runtime. Hand-written renderers in W5 will narrow this to
 * ``import type {{ ReactElement }} from "react"``.
 */
export interface FluxElement {{
  readonly type: string | ((props: Record<string, unknown>) => FluxElement | null);
  readonly props: Record<string, unknown>;
  readonly key: string | number | null;
}}

/** The runtime shape of every flux node in a surface tree. */
export interface FluxNode {{
  component: string;
  id: string;
  [prop: string]: unknown;
}}

/** A loaded token pack (light or dark). Shape follows tokens.schema.json. */
export type FluxTokenPack = Record<string, unknown>;

/** The catalog JSON emitted by the flux build (see catalog.schema.json). */
export type FluxCatalogJson = Record<string, unknown>;

/** Render-time context passed to every renderer. */
export interface FluxRenderContext {{
  theme: FluxTokenPack;
  catalog: FluxCatalogJson;
  renderers: Record<string, FluxRenderer>;
  /** Fallback path for unknown component kinds (basic-catalog degrade). */
  fallback: (node: FluxNode) => FluxElement;
}}

/** The one function every renderer implements. */
export type FluxRenderer = (node: FluxNode, ctx: FluxRenderContext) => FluxElement;
"""


def _scaffold_body(name: str, spec: dict[str, Any]) -> str:
    extends = spec.get("extends") or "Text"
    return f"""{MARKER}
//
// Renderer scaffold for ``{name}`` (extends basic-catalog ``{extends}``).
// Replace this file's body with a pixel-perfect implementation in W5.
// To opt out of re-generation, change the first line of this file to
// ``{USER_MARKER}`` — the build will preserve everything below it.

import type {{ FluxElement, FluxNode, FluxRenderContext, FluxRenderer }} from "./types.js";

/**
 * Default {name} renderer. Emits a minimal container that exposes the
 * node's props via data attributes so the visual runner can detect
 * which component it is looking at even before the real renderer lands.
 */
const {name}: FluxRenderer = (node: FluxNode, _ctx: FluxRenderContext): FluxElement => {{
  const style: Record<string, string | number> = {{
    // CSS custom properties — the theme pack is injected at the surface
    // root by ``<FluxThemeProvider>`` (W5). Authors consume tokens by
    // name, not raw values.
    color: "var(--flux-color-text-primary)",
    backgroundColor: "var(--flux-color-bg-surface)",
    padding: "var(--flux-space-2)",
    borderRadius: "var(--flux-radius-md)",
  }};
  return {{
    type: "div",
    key: node.id,
    props: {{
      "data-flux-component": node.component,
      "data-flux-node-id": node.id,
      style,
      children: ("label" in node && typeof node.label === "string") ? node.label : node.component,
    }},
  }};
}};

export default {name};
"""


def _index_ts(component_names: list[str]) -> str:
    lines: list[str] = [
        MARKER,
        "//",
        "// Re-export map consumed by the visual runner and the UI namespace.",
        "",
        'import type { FluxRenderer } from "./types.js";',
        "",
    ]
    for name in component_names:
        lines.append(f'import {name} from "./{name}.js";')
    lines.append("")
    lines.append("export const renderers: Record<string, FluxRenderer> = {")
    for name in component_names:
        lines.append(f'  "{name}": {name},')
    lines.append("};")
    lines.append("")
    lines.append('export * from "./types.js";')
    lines.append("")
    for name in component_names:
        lines.append(f'export {{ default as {name} }} from "./{name}.js";')
    lines.append("")
    return "\n".join(lines)


def _preserves_user_body(path: Path) -> bool:
    """Return True if the existing file opts out of regeneration."""
    if not path.is_file():
        return False
    try:
        with path.open("r", encoding="utf-8") as fh:
            first_line = fh.readline().rstrip("\n")
    except OSError:
        return False
    return first_line.startswith(USER_MARKER)


def emit(
    catalog: dict[str, Any],
    *,
    root: Path,
) -> list[Path]:
    out_dir = root / "ts" / "src" / "flux" / "renderer"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Always regenerate types.ts — it's the public contract.
    types_path = out_dir / "types.ts"
    types_path.write_text(_TYPES_TS, encoding="utf-8")

    written: list[Path] = [types_path]
    names = sorted((catalog.get("components") or {}).keys())
    for name in names:
        spec = catalog["components"][name]
        # A user may ship either ``<Name>.ts`` (scaffold-style, no JSX) or
        # ``<Name>.tsx`` (real React). Whichever they marked with the user
        # preamble wins; otherwise we emit the scaffold as ``<Name>.ts``.
        tsx_path = out_dir / f"{name}.tsx"
        scaffold_path = out_dir / f"{name}.ts"
        if _preserves_user_body(tsx_path):
            written.append(tsx_path)
            continue
        if _preserves_user_body(scaffold_path):
            written.append(scaffold_path)
            continue
        # Stale .tsx from a previous emit layout — drop it so the re-export
        # map doesn't point at two files for the same component.
        if tsx_path.is_file():
            tsx_path.unlink()
        scaffold_path.write_text(_scaffold_body(name, spec), encoding="utf-8")
        written.append(scaffold_path)

    index_path = out_dir / "index.ts"
    index_path.write_text(_index_ts(names), encoding="utf-8")
    written.append(index_path)
    return written
